'use client';
import React from 'react';
import type { SmartBlockInstance,EducationalImage } from '../../domain/educational/blockSchema';
import { EDUCATIONAL_BLOCK_REGISTRY } from '../../editor/educational/blockRegistry';
import { libraryEntry } from '../../editor/educational/library/catalog';
import { ILLUSTRATION_PRESETS } from '../../editor/educational/library/illustrations';
import { useEditorStore } from '../../editor/stores/editorStore';
import { ImageControls } from './ImageControls';
export function EducationalContentControls({block,elementId}:{block:SmartBlockInstance;elementId:string}){
 const c=block.semanticContent,entry=libraryEntry(block.presetId),content=(patch:Partial<typeof c>)=>useEditorStore.getState().updateSmartBlockContent(elementId,patch);
 if(!entry)return null;
 const field=(key:'hint'|'quote'|'prediction'|'reveal'|'finalAnswer'|'difficulty',label:string)=>c[key]!==undefined?<label className="publication-field" key={key}>{label}<textarea value={c[key]} onChange={e=>content({[key]:e.target.value})}/></label>:null;
 const variant=block.styleOverrides.layoutVariant||EDUCATIONAL_BLOCK_REGISTRY[block.presetId]?.reflowRules.layoutVariant;
 const pictureSlots=entry.composition==='picture'?(variant==='image-grid'?4:variant==='comparison'?2:1):0;
 const imageCount=Math.max(pictureSlots,c.images?.length||0,['picture','story','connection','situation','discovery','burst','prediction','observation'].includes(entry.composition)?1:0);
 function image(index:number,patch:Partial<EducationalImage>){const images=[...(c.images||[])];images[index]={...images[index],...patch};content({images});}
 return <div className="space-y-3">
  {field('hint','Hint')}{field('quote','Character quote')}{field('prediction','Prediction prompt')}{field('reveal','Test / reveal section')}{field('finalAnswer','Worked answer — printed in solved examples')}{field('difficulty','Difficulty marker')}
  {c.vocabulary&&<fieldset className="space-y-3"><legend>Vocabulary entries</legend>{c.vocabulary.map((word,i)=><div key={i} className="border-l-2 border-slate-600 pl-2">{(['word','pronunciation','meaning','example']as const).map(key=><label className="publication-field" key={key}>{key}<textarea value={word[key]||''} onChange={e=>content({vocabulary:c.vocabulary!.map((item,index)=>index===i?{...item,[key]:e.target.value}:item)})}/></label>)}<button type="button" className="publication-button" onClick={()=>content({vocabulary:c.vocabulary!.filter((_,index)=>index!==i)})}>Remove word</button></div>)}<button type="button" className="publication-button" onClick={()=>content({vocabulary:[...c.vocabulary!,{word:'New word',meaning:'Write a meaning.'}]})}>Add word</button></fieldset>}
  {c.formula&&<fieldset className="space-y-2"><legend>Formula</legend><p className="text-xs text-slate-400">Unicode symbols, x^2, x_{1}, and fractions: {String.raw`\frac{1}{2}`}</p><label className="publication-field">Expression<textarea value={c.formula.expression} onChange={e=>content({formula:{...c.formula!,expression:e.target.value}})}/></label><label className="publication-field">Variables — one per line<textarea value={(c.formula.variables||[]).join('\n')} onChange={e=>content({formula:{...c.formula!,variables:e.target.value.split('\n')}})}/></label><label className="publication-field">Units<input value={c.formula.units||''} onChange={e=>content({formula:{...c.formula!,units:e.target.value}})}/></label><label className="publication-field">Diagram<select value={c.formula.diagram||'none'} onChange={e=>content({formula:{...c.formula!,diagram:e.target.value as 'rectangle'|'triangle'|'none'}})}><option value="rectangle">Rectangle</option><option value="triangle">Triangle</option><option value="none">None</option></select></label></fieldset>}
  {c.comparison&&<fieldset className="space-y-2"><legend>Comparison</legend>{(['left','right']as const).map(side=><div key={side}><label className="publication-field">{side} heading<input value={c.comparison![`${side}Label`]} onChange={e=>content({comparison:{...c.comparison!,[`${side}Label`]:e.target.value}})}/></label><label className="publication-field">{side} entries — one per line<textarea value={c.comparison![side].join('\n')} onChange={e=>content({comparison:{...c.comparison!,[side]:e.target.value.split('\n')}})}/></label></div>)}</fieldset>}
  {c.grid&&<fieldset className="space-y-2"><legend>Puzzle grid</legend><label className="publication-field">Rows — use # for a blocked cell and _ for a blank<textarea value={c.grid.rows.join('\n')} onChange={e=>content({grid:{...c.grid!,rows:e.target.value.split('\n')}})}/></label><label className="publication-field">Clues — one per line<textarea value={c.grid.clues.join('\n')} onChange={e=>content({grid:{...c.grid!,clues:e.target.value.split('\n')}})}/></label><label className="publication-field">Teacher solution — excluded from student pages<textarea value={(c.grid.solution||[]).join('\n')} onChange={e=>content({grid:{...c.grid!,solution:e.target.value?e.target.value.split('\n'):undefined}})}/></label></fieldset>}
  {imageCount>0&&<details><summary className="text-xs cursor-pointer">Illustrations & images</summary><div className="space-y-3 pt-3"><label className="publication-field">Preset artwork<select value={block.styleOverrides.illustrationPreset||''} onChange={e=>useEditorStore.getState().updateSmartBlockStyle(elementId,{illustrationPreset:e.target.value||undefined})}><option value="">Subject automatic</option>{ILLUSTRATION_PRESETS.map(preset=><option key={preset}>{preset}</option>)}</select></label>{Array.from({length:imageCount},(_,i)=><details key={i}><summary className="text-xs cursor-pointer">Image {i+1}</summary><ImageControls value={c.images?.[i]||{}} onChange={patch=>image(i,patch)}/><label className="publication-field">Caption<input value={c.images?.[i]?.caption||''} onChange={e=>image(i,{caption:e.target.value})}/></label><button type="button" className="publication-button" onClick={()=>image(i,{src:undefined,originalSrc:undefined,maskDataUrl:undefined})}>Restore preset artwork</button></details>)}{entry.composition==='picture'&&<><button type="button" className="publication-button" onClick={()=>content({images:[...(c.images||Array.from({length:imageCount},()=>({}))),{}]})}>Add image</button><button type="button" className="publication-button" onClick={()=>content({annotations:[...(c.annotations||[]),{imageIndex:0,x:.5,y:.5,label:String((c.annotations?.length||0)+1)}]})}>Add annotation</button>{(c.annotations||[]).map((mark,i)=><div key={i} className="grid grid-cols-2 gap-2"><label className="publication-field">Label<input value={mark.label} onChange={e=>content({annotations:c.annotations!.map((item,k)=>k===i?{...item,label:e.target.value}:item)})}/></label><label className="publication-field">Image<input type="number" min={1} max={imageCount} value={mark.imageIndex+1} onChange={e=>content({annotations:c.annotations!.map((item,k)=>k===i?{...item,imageIndex:Math.max(0,Number(e.target.value)-1)}:item)})}/></label>{(['x','y']as const).map(axis=><label className="publication-field" key={axis}>{axis} position<input type="range" min={0} max={1} step={.01} value={mark[axis]} onChange={e=>content({annotations:c.annotations!.map((item,k)=>k===i?{...item,[axis]:Number(e.target.value)}:item)})}/></label>)}<button type="button" className="publication-button" onClick={()=>content({annotations:c.annotations!.filter((_,k)=>k!==i)})}>Remove marker</button></div>)}</>}</div></details>}
 </div>;
}
