"use client";
import React, { useRef, useState, useEffect } from "react";
import { X, WandSparkles, Check } from "lucide-react";
import type { PageElement } from "../../domain/element/types";
import type { Chapter } from "../../domain/book/types";
import { curriculumSource, editCurriculumBlock, editFramework } from "../../editor/curriculum/actions";
import { aiResultSchema, type AiCurriculumResult } from "../../editor/curriculum/aiSchema";
export function CurriculumAiAssist({ element, chapter, onClose }: { element?: PageElement; chapter?: Chapter; onClose: () => void }) {
  const [instruction,setInstruction]=useState("Draft clear teaching content, examples and questions for this learning block. Keep the learning outcomes and existing factual content."),[busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<AiCurriculumResult>();
  const controller=useRef<AbortController|null>(null);
  useEffect(()=>()=>controller.current?.abort(),[]);
  const source=element?curriculumSource(element):undefined;
  const blocks=source?[source]:Object.values(chapter?.framework?.blocks||{}).filter(b=>!b.isDetached);
  const draft=async()=>{setBusy(true);setError("");setResult(undefined);controller.current=new AbortController();try{
    const response=await fetch("/api/curriculum-assist",{method:"POST",headers:{"Content-Type":"application/json"},signal:controller.current.signal,body:JSON.stringify({instruction,grade:blocks[0]?.curriculum?.grade||3,subject:blocks[0]?.curriculum?.subjectLabel||"Custom",title:chapter?.title||source?.semanticContent.title||"",outcomes:chapter?.learningObjectives||[],blocks:blocks.map(b=>({id:b.id,type:b.curriculum!.type,stage:b.curriculum!.frameworkStage,content:b.semanticContent}))})});
    const data=await response.json();if(!response.ok)throw new Error(data.error||"AI draft failed.");setResult(aiResultSchema.parse(data));
  }catch(e){if(!controller.current?.signal.aborted)setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
  const apply=()=>{if(!result)return;if(element)editCurriculumBlock(element,"Apply reviewed AI draft",b=>({...b,semanticContent:{...b.semanticContent,...result.blocks[0].content},curriculum:{...b.curriculum!,learningOutcomeIds:[...b.curriculum!.learningOutcomeIds]}}));
    else if(chapter)editFramework(chapter.id,"Apply reviewed chapter AI draft",f=>{result.blocks.forEach(row=>{if(f.blocks[row.id])f.blocks[row.id]={...f.blocks[row.id],semanticContent:{...f.blocks[row.id].semanticContent,...row.content}};});return f;});onClose();};
  return <div className="curriculum-modal-backdrop"><section className="curriculum-ai-modal" role="dialog" aria-modal="true" aria-labelledby="curriculum-ai-title"><div className="flex justify-between"><div><span className="curriculum-eyebrow">AUTHORING ASSISTANT</span><h2 id="curriculum-ai-title">Draft {chapter?"chapter content":"learning content"}</h2></div><button className="curriculum-icon-button" onClick={onClose} aria-label="Close AI authoring"><X size={18}/></button></div><p>Drafting sends the selected content to the configured AI provider. Review the result before applying it.</p><label className="curriculum-field">What should the assistant do?<textarea rows={3} value={instruction} onChange={e=>setInstruction(e.target.value)}/></label><button className="curriculum-primary" disabled={busy||!instruction.trim()} onClick={draft}><WandSparkles size={14}/>{busy?"Drafting…":`Draft ${blocks.length} learning ${blocks.length===1?"block":"blocks"}`}</button>{error&&<p role="alert" className="curriculum-error">{error}</p>}{result&&<><div className="curriculum-ai-results">{result.blocks.map(row=><article key={row.id}><strong>{row.content.title}</strong><p>{row.content.introText}</p>{row.content.calloutText && <p><strong>Key idea: </strong>{row.content.calloutText}</p>}{row.content.items.map((item,i)=><p key={i}>{item}</p>)}{row.content.steps.map((step,i)=><p key={`step-${i}`}><strong>Step {step.stepNumber}: {step.title}</strong><br/>{step.body}</p>)}{row.content.questions.map((q,i)=><p key={i}>{i+1}. {q.prompt}{q.options.map((option,j)=><small key={j}>{String.fromCharCode(65+j)}. {option}</small>)}<small>Answer: {q.answer || "No answer provided"} · {q.points} marks</small></p>)}</article>)}</div><button className="curriculum-primary" onClick={apply}><Check size={14}/>Apply reviewed draft</button></> }</section></div>;
}
