/** Display names change; saved element IDs deliberately remain stable. */
export const SIMPLE_ELEMENT_NAMES: Record<string, string> = {
  "chapter-hero": "Chapter Title", "chapter-spark": "Opening Question", "curiosity-question": "Ask a Question",
  "picture-prompt": "Picture Question", "story-hook": "Opening Story", "scenario-starter": "Everyday Situation",
  "observe-tell": "Look and Tell", "prediction-prompt": "Make a Guess", "recall-radar": "What You Know",
  "think-pair-share": "Talk with a Partner", "mystery-starter": "Guess the Answer", "before-we-begin": "Before You Start",
  "learning-mission": "Learning Goals", "learning-outcomes": "What You Will Learn", "success-criteria": "How to Do Well",
  "chapter-roadmap": "Chapter Plan", "concept-journey": "Topic Order", "skill-targets": "Skills to Learn",
  "key-vocabulary": "New Words", "essential-question": "Main Question", "goal-tracker": "Track Your Goals",
  "concept-introduction": "Introduce the Topic", "concept-explorer": "Topic Explanation", "big-idea": "Main Idea",
  "explanation-block": "Explanation", "key-definition": "Definition", "visual-explanation": "Explain with Pictures",
  "worked-example": "Solved Example", "see-it": "Look at an Example", "step-by-step": "Follow the Steps",
  "diagram-explanation": "Explain a Diagram", "process": "How It Works", "example-non-example": "Examples and Non-Examples",
  "story-explanation": "Learn with a Story", "conversation-explanation": "Learn through a Conversation",
  "try-with-me": "Try Together", "guided-practice": "Practice with Help", "complete-together": "Finish Together",
  "let-s-solve": "Solve a Problem", "let-s-read": "Read Together", "let-s-observe": "Look Closely",
  "mini-practice": "Short Practice", "checkpoint": "Check Your Progress", "match-it": "Match the Pairs",
  "fill-it": "Fill the Missing Word", "choose-it": "Choose the Answer", "arrange-it": "Put in Order",
  "label-it": "Add Labels", "trace-it": "Trace the Lines", "speak-it": "Say It Aloud",
  "write-it": "Write Your Answer", "draw-it": "Draw Your Answer", "hands-on": "Practical Activity",
  "math-lab": "Maths Activity", "science-lab": "Science Activity", "language-lab": "Language Activity",
  "activity-zone": "Classroom Task", "life-link": "Everyday Example", "real-world-connection": "Use It in Daily Life",
  "mini-project": "Small Project", "pair-activity": "Partner Activity", "observe-around-you": "Look Around You",
  "make-create": "Make Something", "skill-studio": "Skill Practice", "think-deeper": "Think More",
  "reason-it-out": "Give a Reason", "spot-the-glitch": "Find What Is Wrong", "predict": "What Happens Next?",
  "classify": "Sort into Groups", "analyse": "Look at the Details", "infer": "Use the Clues",
  "brain-booster": "Thinking Game", "mystery": "Solve a Mystery", "logic-corner": "Logic Questions",
  "hots-challenge": "Harder Thinking Questions", "practice-path": "Practice Questions", "power-practice": "Extra Practice",
  "revision": "Quick Review", "chapter-exercise": "Chapter Questions", "concept-review": "Review the Ideas",
  "assessment": "Chapter Test", "mastery-check": "Check Your Learning", "competency-check": "Check Your Skills",
  "3-minute-recall": "Quick Recall", "chapter-snapshot": "Key Points", "concept-map": "Idea Map",
  "my-learning": "What I Learned", "i-can-now": "What I Can Do", "reflection": "Looking Back",
  "confidence-meter": "How Sure Are You?", "learning-journal": "Learning Diary", "what-i-loved": "What I Enjoyed",
  "my-achievement": "My Progress", "world-connection": "Around the World", "history-connection": "From the Past",
  "science-connection": "Science Around Us", "environment-connection": "Our Environment", "culture-connection": "People and Traditions",
  "india-connection": "Around India", "career-connection": "Jobs and Skills", "values-connection": "Good Habits",
  "cross-curricular-link": "Link to Another Subject", "scan-learn": "Scan to Learn", "watch": "Watch a Video",
  "listen": "Listen to Audio", "try-online": "Online Activity", "ai-practice": "Practice with AI",
  "nex-maxx-ai": "Ask the AI Helper", "explore-in-app": "Open in the App", "qr-activity": "Scan for an Activity",
  "what-do-you-notice": "What Do You Notice", "big-question": "Big Question", "timeline": "Timeline",
  "comparison": "Compare Ideas", "cause-effect": "Cause and Effect", "formula": "Formula", "rule": "The Rule",
  "remember": "Remember This", "teacher-note": "Teacher Note", "quick-check": "Quick Check",
  "group-activity": "Group Activity", "home-activity": "Home Activity", "class-activity": "Class Activity",
  "survey": "Class Survey", "experiment": "Experiment", "think-about-it": "Think About It", "why": "Why Is That?",
  "explain-your-thinking": "Explain Your Thinking", "spot-the-error": "Find the Mistake", "what-if": "What If?",
  "compare": "Compare", "challenge-yourself": "Challenge Yourself", "puzzle": "Puzzle",
  "mixed-practice": "Mixed Practice", "test-yourself": "Test Yourself", "challenge-test": "Challenge Test",
  "exam-practice": "Exam Practice", "self-check": "Check Yourself", "what-i-found-difficult": "What Was Hard",
  "need-more-practice": "Need More Practice", "what-s-next": "What Comes Next", "did-you-know": "Did You Know?",
  "amazing-fact": "Amazing Fact", "fun-fact": "Fun Fact", "interactive-practice": "Interactive Practice",
  "digital-challenge": "Online Challenge",
};

/** One plain sentence per element. IDs stay stable; only the library copy changes. */
export const ELEMENT_PURPOSES: Record<string, string> = {
  "chapter-hero": "Open the chapter with a title, a theme, and a question.",
  "chapter-spark": "Start the lesson with one question the class can answer.",
  "curiosity-question": "Invite pupils to ask what they want to find out.",
  "picture-prompt": "Use a picture and a short question to begin talking.",
  "story-hook": "Begin the chapter with a short story.",
  "scenario-starter": "Start from a familiar everyday situation.",
  "observe-tell": "Ask pupils to look and say what they notice.",
  "what-do-you-notice": "Collect first observations before teaching the idea.",
  "prediction-prompt": "Ask pupils to guess what will happen next.",
  "recall-radar": "Find out what the class already knows.",
  "think-pair-share": "Give pupils time to think, then talk with a partner.",
  "mystery-starter": "Open with a puzzle the chapter will solve.",
  "before-we-begin": "Set up materials and expectations before the lesson.",
  "learning-mission": "List the goals pupils should reach in this chapter.",
  "learning-outcomes": "Say what pupils will know or be able to do.",
  "success-criteria": "Show what a good answer or piece of work looks like.",
  "chapter-roadmap": "Preview the order of topics in the chapter.",
  "concept-journey": "Show how the ideas connect from start to finish.",
  "skill-targets": "Name the skills pupils will practise.",
  "key-vocabulary": "Introduce the new words for this chapter.",
  "essential-question": "Pose the main question the chapter answers.",
  "big-question": "Give one big question to return to later.",
  "goal-tracker": "Let pupils tick off goals as they learn them.",
  "concept-introduction": "Introduce the topic in a few clear sentences.",
  "concept-explorer": "Explain the idea with an example pupils recognise.",
  "big-idea": "State the main idea in one place pupils can revisit.",
  "explanation-block": "Explain the concept in simple teaching language.",
  "key-definition": "Give a short definition pupils can remember.",
  "visual-explanation": "Explain the idea with a picture and labels.",
  "worked-example": "Show a solved example, one step at a time.",
  "see-it": "Show a clear example before pupils try alone.",
  "step-by-step": "Break the method into numbered steps.",
  "diagram-explanation": "Explain what a diagram shows.",
  "process": "Show how something works, from start to finish.",
  "timeline": "Put events or steps in time order.",
  "comparison": "Compare two ideas using the same features.",
  "cause-effect": "Show what happened and why it happened.",
  "example-non-example": "Show what counts as an example and what does not.",
  "formula": "Present a formula and what each part means.",
  "rule": "State the rule pupils should follow.",
  "remember": "Highlight the one idea pupils should remember.",
  "vocabulary": "Collect words with simple meanings.",
  "teacher-note": "Leave a note for the teacher beside the teaching.",
  "story-explanation": "Teach the idea through a short story.",
  "conversation-explanation": "Teach the idea through a conversation.",
  "try-with-me": "Work through one example together before independent work.",
  "guided-practice": "Practise with help, prompts, and space to answer.",
  "complete-together": "Finish a partly done example as a class.",
  "let-s-solve": "Solve a problem and show the method.",
  "let-s-read": "Read a short text together and respond.",
  "let-s-observe": "Look closely and record what is there.",
  "mini-practice": "Try a few short questions on the new idea.",
  "quick-check": "Check understanding with one or two questions.",
  "checkpoint": "Pause to see whether pupils are ready to continue.",
  "match-it": "Match pairs such as words and meanings.",
  "fill-it": "Complete a sentence or number sentence.",
  "choose-it": "Choose the correct answer from clear options.",
  "arrange-it": "Put steps, words, or events in order.",
  "label-it": "Add labels to a picture or diagram.",
  "trace-it": "Trace lines, letters, or shapes.",
  "speak-it": "Practise saying the answer aloud.",
  "write-it": "Write an answer on the lines provided.",
  "draw-it": "Draw the answer instead of only writing it.",
  "hands-on": "Do a practical task with materials and steps.",
  "math-lab": "Explore a maths idea with objects or drawings.",
  "science-lab": "Follow a short science activity safely.",
  "language-lab": "Practise speaking, reading, or writing.",
  "activity-zone": "Give the class a task they can start straight away.",
  "life-link": "Connect the idea to everyday life.",
  "real-world-connection": "Show where pupils meet this idea outside school.",
  "mini-project": "Plan and finish a small project.",
  "pair-activity": "Work with a partner on one shared task.",
  "group-activity": "Give a group a task and a way to share the result.",
  "home-activity": "Send a short task pupils can do at home.",
  "class-activity": "Run one activity with the whole class.",
  "observe-around-you": "Notice examples of the idea in the surroundings.",
  "survey": "Collect answers and look for a pattern.",
  "experiment": "Try something, record it, and say what happened.",
  "make-create": "Make something that shows the learning.",
  "skill-studio": "Practise one skill with a clear result.",
  "think-about-it": "Ask a question that needs a reason, not only a fact.",
  "think-deeper": "Push past the first answer with a harder question.",
  "why": "Ask pupils to explain why something is true.",
  "explain-your-thinking": "Leave space to explain the method, not only the answer.",
  "reason-it-out": "Give a reason using what the chapter taught.",
  "spot-the-error": "Find a mistake and correct it.",
  "spot-the-glitch": "Find what does not fit and say why.",
  "what-if": "Change one detail and predict the new result.",
  "predict": "Say what will happen and why.",
  "compare": "Compare two examples and explain the difference.",
  "classify": "Sort items into groups and name the groups.",
  "analyse": "Look at the details and say what they show.",
  "infer": "Use clues to work out something that is not stated.",
  "challenge-yourself": "Try a harder question after the main practice.",
  "brain-booster": "Play a short thinking game on the topic.",
  "puzzle": "Solve a puzzle that uses the chapter idea.",
  "mystery": "Use clues to solve a mystery.",
  "logic-corner": "Answer questions that depend on careful reasoning.",
  "hots-challenge": "Answer harder questions that need explanation.",
  "practice-path": "Move from easier questions to harder ones.",
  "power-practice": "Give extra questions for more practice.",
  "revision": "Review the main ideas before the test.",
  "chapter-exercise": "Answer a set of questions on the whole chapter.",
  "concept-review": "Revisit the important ideas in a short form.",
  "mixed-practice": "Mix question types from across the chapter.",
  "assessment": "Check the chapter with questions and marks.",
  "mastery-check": "See whether pupils can use the idea on their own.",
  "test-yourself": "Let pupils try test-style questions.",
  "challenge-test": "Offer a harder test for pupils who are ready.",
  "competency-check": "Check the skill, not only the remembered fact.",
  "exam-practice": "Practise the kind of question used in a test.",
  "3-minute-recall": "Recall the key points in a short burst.",
  "chapter-snapshot": "Summarise the chapter on one page.",
  "concept-map": "Show how the ideas link to a central topic.",
  "my-learning": "Ask pupils to say what they learned.",
  "self-check": "Let pupils check their own understanding.",
  "i-can-now": "List what pupils can do after the chapter.",
  "reflection": "Look back at the learning and what to do next.",
  "confidence-meter": "Ask how sure pupils feel about the idea.",
  "learning-journal": "Write a short diary entry about the lesson.",
  "what-i-loved": "Note what pupils enjoyed and why.",
  "what-i-found-difficult": "Name what was hard and what would help.",
  "need-more-practice": "Choose what still needs practice.",
  "my-achievement": "Record progress the pupil can see.",
  "what-s-next": "Point to the next step after this chapter.",
  "did-you-know": "Share one interesting fact about the topic.",
  "amazing-fact": "Add a memorable fact pupils can discuss.",
  "fun-fact": "Add a light fact that still teaches something.",
  "world-connection": "Link the idea to somewhere in the world.",
  "history-connection": "Link the idea to something from the past.",
  "science-connection": "Show the science behind an everyday thing.",
  "environment-connection": "Connect the learning to the environment.",
  "culture-connection": "Connect the idea to people and traditions.",
  "india-connection": "Connect the idea to a place or story in India.",
  "career-connection": "Show a job or skill that uses this learning.",
  "values-connection": "Connect the idea to a good habit or value.",
  "cross-curricular-link": "Link this chapter to another subject.",
  "scan-learn": "Point pupils to a checked resource they can open.",
  "watch": "Send pupils to a short video and a question.",
  "listen": "Send pupils to an audio clip and a question.",
  "try-online": "Offer a short online activity with a clear task.",
  "interactive-practice": "Practise the idea in an online activity.",
  "ai-practice": "Practise with an AI helper and a teacher-set task.",
  "digital-challenge": "Give an online challenge with a result to record.",
  "nex-maxx-ai": "Ask the AI helper a question about the lesson.",
  "explore-in-app": "Open a related activity in the app.",
  "qr-activity": "Scan a code to open a checked activity.",
};
