import type { DesignFamily, EducationalBlockCategory, EducationalBlockDefinition, SmartBlockInstance } from "../../domain/educational/blockSchema";

type Content = SmartBlockInstance["semanticContent"];
type Entry = [EducationalBlockCategory, string, string, string, string, string];
/** Educational purpose, public title, two structures, and useful search aliases. */
export const PUBLICATION_CATALOG: Entry[] = [
  ["unit-opening", "Unit Gateway", "panorama", "editorial", "Illustrated panorama", "Typographic opening"],
  ["chapter-structure", "Chapter Launch", "hero", "editorial", "Number city", "Editorial numeral"],
  ["section-heading", "Topic Spotlight", "ribbon", "sidebar", "Numbered ribbon", "Margin marker"],
  ["concept-map", "Learning Map", "radial", "pathway", "Concept constellation", "Learning pathway"],
  ["learning-outcomes", "Learning Targets", "checklist", "milestones", "I can checklist", "Milestone cards"],
  ["prerequisites", "Before We Begin", "split", "question-strip", "Recall and connect", "Readiness strip"],
  ["warm-up", "Ready, Set, Think!", "spotlight", "question-strip", "Visual starter", "Recall and predict"],
  ["essential-question", "The Big Question", "spotlight", "response", "Question spotlight", "Thinking space"],
  ["concept-explanation", "Concept Lens", "split", "comparison", "Explain and illustrate", "Example and non-example"],
  ["vocabulary", "Word Studio", "tiles", "notebook", "Word cards", "Context notebook"],
  ["study-skills", "Learning Toolkit", "sidebar", "steps", "Strategy sidebar", "Three-step routine"],
  ["worked-examples", "See It Step by Step", "steps", "split", "Solution ladder", "Method and verification"],
  ["guided-practice", "Try It Together", "steps", "questions", "Scaffolded solution", "Fading support"],
  ["quick-check", "Checkpoint", "questions", "question-strip", "Question cards", "Confidence strip"],
  ["mental-maths", "Mental Maths Studio", "tiles", "questions", "Number studio", "Explain your shortcut"],
  ["activity-lab", "Discovery Lab", "lab", "stations", "Materials and method", "Activity stations"],
  ["partner-activity", "Think, Pair, Share", "pathway", "split", "Discussion sequence", "Partner roles"],
  ["collaboration", "Team Challenge", "stations", "notebook", "Team task stations", "Planning board"],
  ["investigation", "Question Lab", "lab", "steps", "Predict and observe", "Evidence sequence"],
  ["visual-reasoning", "Look, Notice, Explain", "spotlight", "comparison", "Visual prompt", "Compare and reason"],
  ["common-mistakes", "Spot the Slip", "comparison", "steps", "Find and correct", "Explain and repair"],
  ["critical-thinking", "Reason It Out", "steps", "comparison", "Claim and evidence", "Compare approaches"],
  ["real-world-connect", "Beyond the Page", "split", "spotlight", "Situation and task", "Application spotlight"],
  ["facts-curiosity", "Wonder Window", "spotlight", "sidebar", "Wonder panel", "Curiosity sidebar"],
  ["puzzles-fun", "Puzzle Studio", "tiles", "questions", "Clue tiles", "Logic challenge"],
  ["extension", "Stretch Your Thinking", "spotlight", "response", "Open challenge", "Multiple solutions"],
  ["exercises", "Practice Path", "questions", "tiers", "Practice sequence", "Build, apply, explain"],
  ["assessment-mastery", "Show What You Know", "questions", "stations", "Assessment page", "Skills stations"],
  ["self-assessment", "My Progress Check", "checklist", "notebook", "Skill and evidence", "Next steps"],
  ["reflection", "Pause & Reflect", "response", "comparison", "Reflection journal", "Before and after"],
  ["exit-ticket", "Before You Go", "question-strip", "response", "One-minute check", "Explain, solve, ask"],
  ["revision-recap", "The Big Picture", "radial", "tiles", "Summary map", "Reference cards"],
  ["projects", "Create & Apply", "lab", "stations", "Project brief", "Planning and making"],
  ["cross-subject", "Connected Learning", "comparison", "split", "Subject connections", "Integrated task"],
  ["home-learning", "Take It Further", "notebook", "steps", "Observation notebook", "Everyday investigation"],
  ["diagram-study", "Diagram Explorer", "split", "response", "Observe and label", "Draw and explain"],
  ["data-interpretation", "Data Detective", "tiles", "questions", "Data cards", "Evidence questions"],
  ["reading-response", "Read & Respond", "notebook", "split", "Reading notebook", "Text and evidence"],
  ["ai-explore", "Explore More", "sidebar", "split", "Resource panel", "Explore and record"],
  ["place-value", "Place Value Studio", "place-chart", "expanded", "Place-value chart", "Expanded form"],
  ["abacus", "Build a Number", "abacus", "discs", "Bead abacus", "Place-value discs"],
];

export const PUBLICATION_SAMPLES: Partial<Record<EducationalBlockCategory, Partial<Content>>> = {
  "unit-opening": { title: "A world of numbers", unitBadge: "UNIT 01 · MATHEMATICS", subtitle: "Patterns, place value & possibilities", chapterNumber: "01", calloutText: "How do small digits help us describe a very big world?" },
  "chapter-structure": { title: "Large Numbers", unitBadge: "UNIT 01 · NUMBER SENSE", chapterNumber: "01", subtitle: "Patterns, place value & possibilities", calloutText: "Every digit has a place. Every place tells a story." },
  "section-heading": { title: "Understanding place value", chapterNumber: "1.1", subtitle: "One digit. Different places. Different values." },
  "concept-map": { calloutText: "Large numbers", items: ["Number names", "Place value", "Expanded form", "Comparing numbers", "Rounding", "Roman numerals"] },
  "learning-outcomes": { subtitle: "By the end of this chapter, I can…", items: ["Read and write six-digit numbers.", "Explain the value of each digit.", "Build numbers in expanded form.", "Compare and order large numbers."] },
  "prerequisites": { items: ["Recall: What does each digit in 4,250 represent?", "Connect: What changes when you add 100?" ] },
  "warm-up": { subtitle: "Start with what you already know.", questions: [{ prompt: "Use 2, 4, 6 and 8 to make the greatest four-digit number.", answer: "8,642" }, { prompt: "What changes when 100 is added to 4,250?", answer: "The hundreds digit increases by 1: 4,350." }] },
  "essential-question": { calloutText: "How can the same digit represent different amounts?", items: ["Notice the two 2s in 2,62,354.", "Explain what each one represents."] },
  "concept-explanation": { items: ["Place value: the value of a digit depends on its position.", "Face value: the digit itself, wherever it appears."], calloutText: "In 7,927, the first 7 represents 7,000. The last 7 represents 7." },
  vocabulary: { items: ["Digit — a symbol used to write numbers.", "Place value — the amount a digit represents in a number.", "Period — a group of places used when reading numbers."] },
  "study-skills": { steps: [{ stepNumber: 1, title: "Group", body: "Separate the number into periods." }, { stepNumber: 2, title: "Read", body: "Read each group from left to right." }, { stepNumber: 3, title: "Check", body: "Add the place values to rebuild the number." }] },
  "worked-examples": { subtitle: "Write 3,25,146 in expanded form.", steps: [{ stepNumber: 1, title: "Identify the places", body: "3 lakhs, 2 ten thousands, 5 thousands, 1 hundred, 4 tens and 6 ones." }, { stepNumber: 2, title: "Write the values", body: "3,00,000 + 20,000 + 5,000 + 100 + 40 + 6" }, { stepNumber: 3, title: "Check your answer", body: "Add the parts: they make 3,25,146." }] },
  "guided-practice": { questions: [{ prompt: "2,14,496 = 2,00,000 + ______ + 4,000 + ______ + 90 + 6", answer: "10,000; 400" }, { prompt: "Explain how you checked your answer." }] },
  "quick-check": { questions: [{ prompt: "What is the value of 7 in 5,72,406?", answer: "70,000" }, { prompt: "Write 3,00,000 + 20,000 + 4,000 + 80 + 6 as a number.", answer: "3,24,086" }] },
  "mental-maths": { questions: [{ prompt: "49 + 36 = ? Explain your adjustment.", answer: "85; use 50 + 35." }, { prompt: "25 × 16 = ? Try regrouping.", answer: "400; use 100 × 4." }, { prompt: "999 + 101 = ?", answer: "1,100" }, { prompt: "5,000 − 999 = ?", answer: "4,001" }] },
  "activity-lab": { subtitle: "Build it. Read it. Explain it.", materials: ["Place-value discs", "Paper", "Pencil"], steps: [{ stepNumber: 1, title: "Build", body: "Represent 3,25,146 with place-value discs." }, { stepNumber: 2, title: "Exchange", body: "Swap your model with a partner and read the number." }, { stepNumber: 3, title: "Record", body: "Draw your model and write its expanded form." }], footnote: "Reflect: how did the columns help you read the number?" },
  "partner-activity": { items: ["THINK · Build a six-digit number.", "PAIR · Explain each digit’s value to your partner.", "SHARE · Compare your strategies with the class."] },
  collaboration: { items: ["Builder: create a place-value model.", "Reader: write the number in words.", "Checker: verify the expanded form."] },
  investigation: { materials: ["Ruler", "Paper", "Classroom objects"], steps: [{ stepNumber: 1, title: "Predict", body: "Which object will be longest?" }, { stepNumber: 2, title: "Measure", body: "Measure three objects using the same unit." }, { stepNumber: 3, title: "Explain", body: "Compare your measurements with your prediction." }] },
  "visual-reasoning": { items: ["What is the same about 3,030 and 3,003?", "What is different? Explain using place value."] },
  "common-mistakes": { items: ["The slip: ‘The 5 in 5,204 has a value of 500.’", "The correction: the 5 is in the thousands place, so its value is 5,000."], calloutText: "Check the position before naming the value." },
  "critical-thinking": { items: ["Claim: a number with more digits is always greater.", "Evidence: test this claim using positive whole numbers.", "Reasoning: explain why the place on the left matters."] },
  "real-world-connect": { calloutText: "A library has 24,580 books. It receives 1,250 more.", questions: [{ prompt: "Estimate the new total, then calculate exactly.", answer: "25,830 books." }, { prompt: "Explain why an estimate is useful." }] },
  "facts-curiosity": { calloutText: "Zero holds a place even when there is nothing in that place.", items: ["Compare 405 and 45.", "What job is the zero doing?"] },
  "puzzles-fun": { items: ["I am a five-digit number.", "My ten-thousands digit is 3.", "All my other digits are 2.", "Who am I? Explain your reasoning."] },
  extension: { calloutText: "How many different numbers can you make with 1, 2, 3 and 4, using each digit once?", items: ["Find a systematic way to list them.", "Explain how you know none are missing."] },
  exercises: { questions: [{ prompt: "Write 64,247 in words.", answer: "Sixty-four thousand two hundred forty-seven." }, { prompt: "Write five lakh eight thousand nine in figures.", answer: "5,08,009" }, { prompt: "Compare 4,44,344 and 4,43,444. Explain.", answer: "4,44,344 is greater." }] },
  "assessment-mastery": { questions: [{ prompt: "Write 7,12,249 in expanded form.", points: 2, answer: "7,00,000 + 10,000 + 2,000 + 200 + 40 + 9" }, { prompt: "Create a six-digit number with 5 in the thousands place.", points: 1 }, { prompt: "Explain why the two 4s in 4,40,000 have different values.", points: 2 }] },
  "self-assessment": { items: ["I can name each place in a six-digit number.", "I can explain my expanded form.", "My next step is to practise…"] },
  reflection: { items: ["I used to think…", "Now I understand…", "One question I still have is…"] },
  "exit-ticket": { questions: [{ prompt: "Explain the value of 6 in 2,62,354.", answer: "60,000" }, { prompt: "Write one question you would like to explore." }] },
  "revision-recap": { calloutText: "Place value", items: ["Read in periods", "Name each place", "Expand the values", "Compare from the left"] },
  projects: { materials: ["Local data", "Paper", "Colour pencils"], steps: [{ stepNumber: 1, title: "Collect", body: "Find three examples of large numbers around you." }, { stepNumber: 2, title: "Represent", body: "Show each number using a chart and expanded form." }, { stepNumber: 3, title: "Present", body: "Create a poster explaining what the numbers mean." }] },
  "cross-subject": { items: ["Mathematics: compare distances using place value.", "Geography: read distances between cities on a map."] },
  "home-learning": { items: ["Find a large number on a package or newspaper.", "Read it aloud and explain what it describes.", "Record it in words and expanded form."] },
  "diagram-study": { calloutText: "Draw a place-value model for 21,496.", items: ["Label each column.", "Explain how your diagram represents the number."] },
  "data-interpretation": { items: ["Library A: 12,450 books", "Library B: 14,205 books", "Library C: 12,540 books"], questions: [{ prompt: "Which library has the most books? Explain your comparison.", answer: "Library B." }] },
  "reading-response": { passage: "Mira arranged number cards on her desk. She moved a 4 from the ones place to the thousands place. The digit looked the same, but the number changed. ‘The position matters,’ she said.", questions: [{ prompt: "What changed when Mira moved the 4? Use evidence from the passage." }] },
  "ai-explore": { calloutText: "Explore another way to represent the same number.", items: ["Try a chart and a drawing.", "Explain which representation helped you most."], footnote: "Add a verified resource address in the content editor, if needed." },
  "place-value": { numberValue: 325146, numberSystem: "indian", subtitle: "Every digit has a place. Every place has a value." },
  abacus: { numberValue: 214496, numberSystem: "indian", subtitle: "Read each column from left to right." },
};
const families: DesignFamily[] = ["nex-spectrum", "nex-editorial", "nex-play", "nex-discovery", "nex-studio", "nex-future"];
export const PUBLICATION_BLOCKS: Record<string, EducationalBlockDefinition> = Object.fromEntries(
  PUBLICATION_CATALOG.flatMap(([category, title, a, b, nameA, nameB], index) => [a, b].map((layout, variant) => {
    const id = `studio-${category}-${variant + 1}`;
    const content: Content = { title, ...PUBLICATION_SAMPLES[category] };
    const family: DesignFamily = layout === "editorial" ? "nex-editorial" : layout === "hero" ? "nex-spectrum" : layout === "lab" ? "nex-discovery" : layout === "stations" ? "nex-studio" : families[(index + variant) % families.length];
    const def: EducationalBlockDefinition = {
      id, archetypeId: category, category, name: `${title} · ${variant === 0 ? nameA : nameB}`,
      description: `${title}. ${variant === 0 ? nameA : nameB}. Editable content, vector artwork and print-safe geometry.`,
      family, version: 2, collectionVersion: 2,
      supportedSubjects: category === "place-value" || category === "abacus" || category === "mental-maths" ? ["mathematics"] : ["general"],
      supportedGrades: ["primary-upper", "primary-lower", "middle-school", "secondary-plus", "early-years"],
      tags: [title, category, layout, ...(category === "concept-map" ? ["lesson schema", "mind map"] : []), ...(category === "learning-outcomes" ? ["learning outcomes", "objectives"] : [])],
      minDimensions: { widthPt: 180, heightPt: 60 },
      defaultDimensions: { widthPt: 480, heightPt: category === "chapter-structure" || category === "unit-opening" ? 210 : 180 },
      reflowRules: { layoutVariant: layout, verticalGrowthStrategy: "expand-container" },
      defaultBackgroundStyle: { type: "subtle-tint", color: "#ffffff", cornerRadiusPt: 10 },
      slots: Object.entries(content).map(([slotId, defaultContent]) => ({ slotId, label: slotId, type: slotId === "items" || slotId === "materials" ? "item-list" : slotId === "steps" ? "steps-list" : "text", required: slotId === "title", defaultContent })),
    };
    return [id, def];
  }))
);
