import { CalloutKey } from "./tokens";

export interface DesignSpec {
  layout: string;
  name: string;
  description: string;
  callout?: CalloutKey;
}

export const CHAPTER_SPECS: DesignSpec[] = [
  { layout: "row{number:display~26, stack{kicker:smallcaps, title:1.2, subtitle}}", name: "Offset Monument", description: "A large chapter number beside a stacked title and subtitle." },
  { layout: "row@end{number:display~22, stack{title:1.15, rule:short}}", name: "Baseline Number", description: "The number sits on the same baseline as a title and a short rule." },
  { layout: "stack@center{kicker:smallcaps, rule:double, title:1.2, rule:hairline, subtitle}", name: "Centred Double Rule", description: "A centred serif title held between a double rule and a hairline." },
  { layout: "stack@center{kicker:smallcaps, row{rule:flex, ornament:diamond, rule:flex}, title:1.15, subtitle}", name: "Diamond Interval", description: "A small diamond breaks the rule above a centred chapter title." },
  { layout: "row{rail:thick, stack{kicker:smallcaps, title:1.2, subtitle}}", name: "Thick Accent Rail", description: "A heavy left rail with a small chapter label and the title." },
  { layout: "row{rail:hairline, stack{number:chip, title:1.15, subtitle}}", name: "Hairline Rail", description: "A fine left rule, a chip number, and a title with room to wrap." },
  { layout: "row{stack@center~22{kicker:smallcaps, number:display}, rule:v, stack{title:1.15, subtitle}}", name: "Split Number Column", description: "Number and title sit in separate columns divided by a vertical rule." },
  { layout: "row@end{number:display~24, stack{title:1.2, subtitle}}", name: "Bottom-Aligned Split", description: "The display number aligns to the foot of a two-line title." },
  { layout: "band#accent{stack@center{kicker:smallcaps, title:1.25, subtitle}}", name: "Full Colour Band", description: "A solid accent band with high-contrast centred type." },
  { layout: "stack{band#accent{row{kicker:smallcaps, number:modest}}, title:1.2, subtitle}", name: "Inset Chapter Band", description: "Only the label band is coloured. The title stays on the page." },
  { layout: "stack{band#accent{kicker:smallcaps}, title:1.15, rule:short, subtitle}", name: "Kicker Band", description: "A narrow coloured kicker, then the title, a short rule, and a subtitle." },
  { layout: "stack{row{ornament:square, kicker:smallcaps}, title:1.2, rule:full, subtitle}", name: "Corner Square", description: "A small geometric square marks the kicker above a full rule." },
  { layout: "corners{stack@center{number:display, title:1.15, subtitle}}", name: "Open Corner Frame", description: "Corner marks frame a centred number and title with open space inside." },
  { layout: "stack{title:1.25, rule:short, subtitle}", name: "Short Editorial Rule", description: "The title, a short rule, and a one-line subtitle. No number." },
  { layout: "stack{kicker:smallcaps, title:1.2, rule:full, subtitle}", name: "Full Editorial Rule", description: "A small-caps label, the title, and a rule that runs the full measure." },
  { layout: "row{number:chip, title:1.15}", name: "Compact Chip", description: "A compact opener: chip number and title on one line." },
  { layout: "row{kicker:smallcaps, number:modest, title:1.1}", name: "Inline Chapter Label", description: "Label, number, and title share a single compact line." },
  { layout: "row{stack~20{number:display, kicker:smallcaps}, stack{title:1.15, rule:short, subtitle}}", name: "Margin Stack", description: "The number stacks in the margin. The title stacks in the main column." },
  { layout: "row{number:vertical, stack{kicker:smallcaps, title:1.2, subtitle}}", name: "Vertical Margin Label", description: "The chapter number reads downward in the margin beside the title." },
  { layout: "row{stack{kicker:smallcaps, title:1.2, subtitle}, panel:tint~30}", name: "Plate Beside Title", description: "The title keeps the wide column. A labelled plate holds the side." },
  { layout: "row@center{number:circle, stack{title:1.15, subtitle}}", name: "Circled Number", description: "A circular number sits beside a centred title block." },
  { layout: "stack{title:1.4, rule:short, row@center{kicker:smallcaps, number:modest}}", name: "Monument Stack", description: "The title is the largest element. The number sits quietly underneath." },
  { layout: "row{number:drop, stack{kicker:smallcaps, title:1.15, subtitle}}", name: "Drop Number", description: "The number drops beside the title the way a drop cap drops beside prose." },
  { layout: "row@center{ornament:bracketL, stack{title:1.2, subtitle}, ornament:bracketR}", name: "Bracketed Title", description: "Light brackets hold a centred title without a heavy frame." },
  { layout: "stack{rule:thick, kicker:smallcaps, title:1.2, rule:hairline}", name: "Heavy Top Rule", description: "A strong rule opens the chapter. A hairline closes the title." },
  { layout: "stack{band#accent{stack@center{number:display, kicker:smallcaps}}, title:1.15, subtitle}", name: "Number Band", description: "The number lives in its own band. The title begins beneath it." },
  { layout: "stack@right{kicker:smallcaps, title:1.2, rule:short, subtitle}", name: "Right Literary Close", description: "A right-aligned chapter close for verso openings and epigraph pages." },
  { layout: "stack{kicker:smallcaps, title:1.15, rule:short, subtitle:italic}", name: "Epigraph Opener", description: "Title, short rule, and an italic subtitle used as an epigraph." },
  { layout: "stack@center{number:display, rule:short, title:1.2, subtitle}", name: "Number Above Title", description: "The number stands alone, then a short rule, then the title." },
  { layout: "row{stack#accent~34{number:display, kicker:smallcaps}, stack{title:1.15, subtitle}}", name: "Two-Tone Split", description: "A coloured number column beside the title on the page ground." },
];

export const HEADING_SPECS: DesignSpec[] = [
  { layout: "row{number:modest, title, rule:short}", name: "Numbered Short Rule", description: "Section number, title, and a short rule under the line." },
  { layout: "stack{rule:full, row{number:modest, title}}", name: "Rule Above Heading", description: "A full rule introduces the number and title." },
  { layout: "stack{row{rule:flex, number:chip, rule:flex}, title}", name: "Number in the Gap", description: "The section number interrupts a rule, with the title below." },
  { layout: "row{number:chip, title, rule:hairline}", name: "Chip and Hairline", description: "A small numbered chip, the title, and a hairline." },
  { layout: "stack{number:modest, title, subtitle, rule:short}", name: "Numbered Deck", description: "Number, title, deck, and a short closing rule." },
  { layout: "stack{kicker:smallcaps, title}", name: "Small-Caps Kicker", description: "A small-caps label stacked over the section title." },
  { layout: "stack{kicker:chip, title, rule:short}", name: "Chip Kicker", description: "The section label sits in a chip above a short rule." },
  { layout: "stack@center{kicker:smallcaps, title, rule:double}", name: "Centred Double Heading", description: "Centred label and title closed by a double rule." },
  { layout: "stack{kicker:chip, title, subtitle}", name: "Kicker with Deck", description: "Chip label, title, and a secondary deck line." },
  { layout: "row{rail:hairline, stack{kicker:plain, title}}", name: "Hairline Kicker Rail", description: "A fine rail, a plain label, and the title." },
  { layout: "row{number:display~18, stack{title}}", name: "Display Index", description: "A larger index number in its own column beside the title." },
  { layout: "row{number:display~18, stack{title, rule:short}}", name: "Indexed Rule", description: "Display index, title, and a short rule in the text column." },
  { layout: "row{number:modest~16, stack{title, subtitle}}", name: "Index and Deck", description: "A modest index column with a title and deck." },
  { layout: "row{number:chip~16, stack{title, rule:hairline}}", name: "Chip Index", description: "The index is a chip. The title closes on a hairline." },
  { layout: "row@end{number:modest, title}", name: "End-Aligned Number", description: "Number and title share a line, aligned to the foot of the text." },
  { layout: "stack@center{title, rule:short}", name: "Centred Short Rule", description: "A centred section title with a short rule and no number." },
  { layout: "stack@center{title, rule:double, subtitle}", name: "Centred Deck", description: "Centred title, double rule, and a deck beneath." },
  { layout: "stack@center{ornament:diamond, title, subtitle}", name: "Diamond Heading", description: "A single diamond, then a centred title and deck." },
  { layout: "stack@center{kicker:smallcaps, title, rule:short}", name: "Centred Label Rule", description: "Small-caps label, centred title, short rule." },
  { layout: "stack@center{rule:hairline, title, rule:hairline}", name: "Rules Above and Below", description: "The title is held between two hairlines." },
  { layout: "row{number:drop, stack{title, subtitle}}", name: "Hanging Drop Number", description: "The number hangs beside the title like a small drop cap." },
  { layout: "row{number:modest, stack{title, rule:full, subtitle}}", name: "Hanging Full Rule", description: "Number in the margin, title, full rule, then the deck." },
  { layout: "row{number:chip, stack{kicker:smallcaps, title}}", name: "Chip Over Label", description: "A chip number beside a small-caps label and title." },
  { layout: "row{rail:thick, number:modest, title}", name: "Rail and Inline Number", description: "A thick rail, then the number and title on one line." },
  { layout: "stack@right{number:modest, title, subtitle}", name: "Right-Aligned Deck", description: "A right-aligned numbered heading with a deck." },
  { layout: "stack#tint{row{number:chip, title}}", name: "Tinted Number Row", description: "Number and title sit together on a quiet tint." },
  { layout: "stack#surface{label:chip, title}", name: "Boxed Label Heading", description: "A surface card with a label chip and the section title." },
  { layout: "stack{label:chip, title, subtitle}", name: "Label Outside the Title", description: "The label is a chip. The title and deck sit in open space." },
  { layout: "row{label:chip, rule:flex, title}", name: "Label Then Rule", description: "A chip label, a flexible rule, and the title at the far side." },
  { layout: "stack{rule:thick, title, rule:hairline}", name: "Thick Then Fine", description: "A heavy rule, the title, and a fine rule beneath." },
  { layout: "stack{title, rule:short}", name: "Underline Left", description: "A plain title with a short underline. Useful for frequent subsections." },
  { layout: "stack@center{title, rule:short, subtitle}", name: "Centred Underline Deck", description: "Centred title, short underline, and a deck." },
  { layout: "stack{title, subtitle, rule:double}", name: "Deck Then Double Rule", description: "Title and deck, closed by a double rule." },
  { layout: "row{title, rule:flex, number:chip}", name: "Title Then Number", description: "The title leads. The number chip closes the line." },
  { layout: "stack{rule:dotted, title, subtitle}", name: "Dotted Intro", description: "A dotted rule, then the title and deck." },
  { layout: "row{kicker:smallcaps~22, stack{title, subtitle}}", name: "Margin Label", description: "The section label sits in the margin. The title is in the column." },
  { layout: "row{number:vertical, stack{title, rule:short}}", name: "Vertical Index", description: "A vertical section number beside the title and a short rule." },
  { layout: "row{rail:thick, stack{kicker:smallcaps, title}}", name: "Thick Rail Heading", description: "A thick rail with a small-caps label and the title." },
  { layout: "stack{kicker:smallcaps, title, rule:short, subtitle}", name: "Label Rule Deck", description: "Label, title, short rule, and deck, stacked in that order." },
  { layout: "row{number:circle, title}", name: "Circled Section Number", description: "A small circle holds the section number beside the title." },
  { layout: "stack{title:1.15, subtitle}", name: "Two-Line Deck", description: "A slightly larger title with a deck and no rule." },
  { layout: "stack@center{title:1.1, subtitle, rule:short}", name: "Centred Two-Line", description: "Centred title and deck, finished with a short rule." },
  { layout: "stack{title, rule:short, subtitle}", name: "Rule Between Lines", description: "The short rule sits between the title and the deck." },
  { layout: "row{number:chip, stack{title, subtitle}, ornament:square}", name: "Chip Title Square", description: "Chip number, stacked title, and a small square mark." },
  { layout: "stack@right{kicker:smallcaps, title, rule:short}", name: "Right Label Rule", description: "Right-aligned label, title, and short rule." },
  { layout: "row{stack~24{kicker:smallcaps, number:modest}, rule:v, stack{title, subtitle}}", name: "Split Meta Column", description: "Label and number in one column, title and deck in the other." },
  { layout: "row{title, stack@right{kicker:smallcaps, number:modest}}", name: "Title with Trailing Meta", description: "The title takes the line. Label and number sit at the right." },
  { layout: "stack{rule:double, row{number:modest, title}, rule:hairline}", name: "Double Rule Sandwich", description: "A double rule above the numbered title and a hairline below." },
  { layout: "band#accent{row{number:chip, title}}", name: "Accent Heading Band", description: "A full-width accent band with a chip number and the title." },
  { layout: "row{rail:thick, stack{title, rule:short, subtitle}}", name: "Rail Title Deck", description: "Thick rail, title, short rule, and deck." },
];

export const RUNNING_SPECS: DesignSpec[] = [
  { layout: "row{meta:chapter, rule:flex, meta:page}", name: "Chapter and Folio", description: "Chapter title on the left, a flexible rule, and the folio on the right." },
  { layout: "stack{rule:hairline, row{meta:chapter, meta:page}}", name: "Hairline Above", description: "A hairline sits above the chapter title and page number." },
  { layout: "stack{row{meta:chapter, meta:page}, rule:hairline}", name: "Hairline Below", description: "Chapter and folio, with the hairline under the line of type." },
  { layout: "stack@center{meta:chapter:smallcaps, rule:short, meta:page}", name: "Centred Small Caps", description: "A centred running head in small caps, a short rule, then the folio." },
  { layout: "row{meta:section, rule:dotted, meta:page}", name: "Dotted Section Folio", description: "Section name and page number joined by a dotted rule." },
  { layout: "row{kicker:smallcaps, meta:chapter, rule:flex, number:chip}", name: "Kicker and Chip Folio", description: "A small-caps kicker, the chapter, and the page in a chip." },
  { layout: "stack{rule:thick, row{meta:chapter, meta:page}}", name: "Heavy Running Rule", description: "A heavier rule marks the top of the page above the running head." },
  { layout: "row{rail:thick, meta:chapter, rule:flex, meta:page}", name: "Rail Running Head", description: "A short rail, the chapter title, and the folio." },
  { layout: "row{ornament:square, meta:chapter, rule:flex, meta:page}", name: "Square Tick Folio", description: "A small square tick before the chapter title and folio." },
  { layout: "row{meta:chapter, rule:flex, meta:section, rule:flex, meta:page}", name: "Three-Part Head", description: "Chapter, section, and page, separated by flexible rules." },
  { layout: "stack{row{meta:chapter, meta:page}, rule:double}", name: "Double Rule Footer", description: "A running line closed by a double rule. Suitable as a footer." },
  { layout: "stack@center{rule:short, meta:page, rule:short}", name: "Folio Between Rules", description: "The page number alone, centred between two short rules." },
  { layout: "row@end{meta:page}", name: "Outside Folio", description: "Only the page number, set to the outside edge." },
  { layout: "stack@center{meta:page}", name: "Centred Folio", description: "A centred page number with no other furniture." },
  { layout: "row{meta:section:smallcaps, meta:chapter, meta:page}", name: "Section Chapter Page", description: "Section, chapter, and page in one quiet line." },
  { layout: "stack{rule:double, row{kicker:smallcaps, meta:chapter, meta:page}, rule:double}", name: "Double Sandwich Head", description: "The running line is held between two double rules." },
  { layout: "row{label:chip, rule:flex, meta:page}", name: "Chip and Folio", description: "A chip label on the left and the folio on the right." },
  { layout: "row{meta:chapter, stack@right{meta:section, meta:page}}", name: "Stacked Right Folio", description: "Chapter on the left. Section and page stack on the right." },
  { layout: "corners{row{meta:chapter, rule:flex, meta:page}}", name: "Corner-Marked Head", description: "Small corner marks around a chapter-and-folio line." },
  { layout: "row{rule:v, stack{meta:section, meta:chapter}, rule:flex, number:modest}", name: "Vertical Tick Head", description: "A vertical rule, stacked section and chapter, then the page number." },
];

export const BODY_SPECS: DesignSpec[] = [
  { layout: "stack{body}", name: "Ragged Paragraph", description: "A standard readable paragraph with a comfortable measure." },
  { layout: "stack{body:lead}", name: "Small-Caps Lead", description: "The opening words are set in small caps, then the paragraph continues." },
  { layout: "stack{body:drop}", name: "Drop-Cap Opening", description: "A two-line drop cap begins an introduction." },
  { layout: "stack{body:narrow}", name: "Narrow Measure", description: "A narrower measure for an introduction or a pull of prose." },
  { layout: "stack@center{body:narrow}", name: "Centred Narrow Intro", description: "A centred narrow introduction for chapter decks." },
  { layout: "stack{kicker:smallcaps, body}", name: "Labelled Paragraph", description: "A small-caps label introduces the paragraph." },
  { layout: "stack{body, rule:short}", name: "Paragraph and Rule", description: "Body text closed by a short editorial rule." },
  { layout: "row{rail:hairline, body}", name: "Rail Paragraph", description: "A hairline rail marks an indented block of prose." },
  { layout: "stack{rule:thick, body}", name: "Rule Then Prose", description: "A strong rule separates this passage from what came above." },
  { layout: "stack#surface{body}", name: "Surface Passage", description: "The paragraph sits on a quiet surface, useful for an aside." },
  { layout: "stack#tint{kicker:smallcaps, body}", name: "Tinted Introduction", description: "A tinted introduction with a small-caps label." },
  { layout: "stack{label:chip, body}", name: "Chip Introduction", description: "A chip label, such as Introduction, above the paragraph." },
  { layout: "stack{caption}", name: "Plain Caption", description: "A caption set under a figure, without an extra rule." },
  { layout: "stack{rule:short, caption}", name: "Caption Under Rule", description: "A short rule, then the caption." },
  { layout: "row{figure:frame~34, stack{caption}}", name: "Side Caption", description: "A small frame and the caption beside it." },
  { layout: "stack{figure:frame, caption}", name: "Frame and Caption", description: "The frame sits above its caption." },
  { layout: "stack{label:chip, caption}", name: "Numbered Caption Chip", description: "A figure chip, then the caption." },
  { layout: "row{number:chip, caption}", name: "Inline Figure Number", description: "The figure number and caption share one line." },
  { layout: "stack@center{caption, rule:short}", name: "Centred Caption", description: "A centred caption finished with a short rule." },
  { layout: "stack{caption, meta:credit}", name: "Caption and Credit", description: "Caption plus a separate credit line." },
  { layout: "row{rail:thick, stack{caption, meta:credit}}", name: "Rail Caption", description: "A rail beside the caption and its credit." },
  { layout: "stack{kicker:smallcaps, body:lead}", name: "Lead with Label", description: "A label and a small-caps lead-in for the first paragraph of a section." },
  { layout: "stack{body:italic}", name: "Italic Passage", description: "An italic passage for a short reading or extract." },
  { layout: "corners{stack{caption}}", name: "Cornered Caption", description: "Corner marks around a caption block." },
];

export const QUOTE_SPECS: DesignSpec[] = [
  { layout: "stack{quote:mark, attr}", name: "Large Quotation Mark", description: "An oversized quotation mark, the passage, and the attribution." },
  { layout: "row{rail:thick, stack{quote, attr}}", name: "Quote with Rail", description: "A thick rail beside the quotation and its source." },
  { layout: "stack@center{quote, rule:short, attr}", name: "Centred Epigraph", description: "A centred quotation, a short rule, and the attribution." },
  { layout: "band#tint{stack{quote, attr}}", name: "Tinted Quotation", description: "The quotation sits on a tint, with the source beneath." },
  { layout: "stack@center{ornament:brackets, quote, attr}", name: "Bracket Interval", description: "A bracket ornament, then a centred quotation." },
  { layout: "stack{rule:double, quote, rule:double, attr}", name: "Double-Rule Extract", description: "The extract is held between double rules." },
  { layout: "row{number:display~16, stack{quote, attr}}", name: "Numbered Extract", description: "A display number beside a quotation, for a sequence of extracts." },
  { layout: "stack@center{quote:mark, rule:short, attr}", name: "Marked Epigraph", description: "A centred mark, a short rule, and the attribution." },
  { layout: "stack{kicker:smallcaps, quote, attr}", name: "Labelled Quotation", description: "A small-caps label such as Epigraph above the quotation." },
  { layout: "row{ornament:square, stack{quote, attr}}", name: "Square-Marked Quote", description: "A small square mark beside the quotation." },
  { layout: "stack@right{quote, rule:short, attr}", name: "Right-Aligned Extract", description: "A right-aligned quotation for a literary close." },
  { layout: "corners{stack@center{quote, attr}}", name: "Cornered Epigraph", description: "Corner marks around a centred epigraph." },
  { layout: "stack{quote, attr}", name: "Plain Extract", description: "Quotation and attribution, with no extra ornament." },
  { layout: "band#accent{stack@center{quote, attr}}", name: "Accent Extract", description: "A high-contrast band for a short highlighted passage." },
  { layout: "stack{ornament:asterism, quote, attr}", name: "Asterism Extract", description: "An asterism marks a pause before the quotation." },
  { layout: "row{rail:hairline, stack{kicker:smallcaps, quote, attr}}", name: "Fine Rail Epigraph", description: "A hairline rail, a label, the quotation, and the source." },
];

export const LEARNING_SPECS: DesignSpec[] = [
  { layout: "stack#callout{label:chip, items:check}", name: "Objective Checklist", description: "A labelled checklist of learning objectives.", callout: "info" },
  { layout: "row{rail:thick, stack#callout{label, items:number}}", name: "Numbered Objectives", description: "Numbered objectives beside a thick rail.", callout: "info" },
  { layout: "stack#callout{label:smallcaps, rule:short, items:check}", name: "Ruled Objective List", description: "A small-caps label, a short rule, and a checklist.", callout: "info" },
  { layout: "band#tint{stack{label, items:check}}", name: "Tinted Objective Band", description: "Objectives on a tinted band, still labelled in words.", callout: "info" },
  { layout: "stack#callout{term, rule:short, def}", name: "Stacked Definition", description: "The term, a short rule, and the definition.", callout: "definition" },
  { layout: "row{term:chip, stack{def, meta:example}}", name: "Inline Term", description: "The term is a chip beside the definition and an example.", callout: "definition" },
  { layout: "row{rail:hairline, stack#callout{kicker:smallcaps, term, def}}", name: "Margin Definition", description: "A hairline, a label, the term, and the definition.", callout: "definition" },
  { layout: "stack@center#callout{kicker, term, rule:short, def}", name: "Centred Term", description: "A centred term for a featured definition.", callout: "definition" },
  { layout: "row{rail:thick, stack#callout{label, body}}", name: "Note with Rail", description: "A note labelled in words, marked by a rail rather than colour alone.", callout: "note" },
  { layout: "stack#callout{label:chip, body, rule:dotted}", name: "Tip with Dotted Close", description: "A tip label, the note, and a dotted rule.", callout: "note" },
  { layout: "corners{stack#callout{label, body}}", name: "Warning Frame", description: "Corner marks and the word Warning. Colour supports the label.", callout: "warning" },
  { layout: "stack#callout{rule:double, label:smallcaps, body, rule:double}", name: "Remember Band", description: "The word Remember between double rules.", callout: "summary" },
  { layout: "stack#callout{label, items:check}", name: "Summary Checklist", description: "A summary title and a checklist of takeaways.", callout: "summary" },
  { layout: "stack#callout{label:chip, items:number}", name: "Numbered Summary", description: "Numbered takeaways under a summary chip.", callout: "summary" },
  { layout: "row{number:modest, stack#callout{label, items:check}}", name: "Indexed Summary", description: "A section index beside the summary list.", callout: "summary" },
  { layout: "stack#callout{label, rule:full, items:number, rule:short}", name: "Ruled Takeaways", description: "A full rule, numbered takeaways, and a short close.", callout: "summary" },
  { layout: "stack#callout{kicker:smallcaps, term, meta:speech, def}", name: "Vocabulary Stack", description: "Label, term, part of speech, and definition.", callout: "definition" },
  { layout: "row{term, stack{meta:speech, def}}", name: "Vocabulary Inline", description: "The term leads. Speech and definition follow in the second column.", callout: "definition" },
  { layout: "band#tint{stack{term, def}}", name: "Tinted Vocabulary", description: "Term and definition on a tint, without an extra icon.", callout: "definition" },
  { layout: "stack#callout{term, rule:short, def, meta:example}", name: "Term Example", description: "Term, definition, and a labelled example sentence.", callout: "definition" },
  { layout: "stack#callout{label:chip, body}", name: "Key Concept", description: "A concept label and a short explanation.", callout: "info" },
  { layout: "row{ornament:square, stack#callout{label, body}}", name: "Marked Concept", description: "A square mark beside the concept label and explanation.", callout: "info" },
  { layout: "stack@center#callout{label:smallcaps, rule:short, body}", name: "Centred Concept", description: "A centred concept statement with a short rule.", callout: "info" },
  { layout: "row{rail:thick, stack#callout{label, rule:short, body}}", name: "Rail Concept", description: "A rail, the concept label, a rule, and the explanation.", callout: "info" },
  { layout: "stack#callout{label, quote, meta:credit}", name: "Fact with Source", description: "A fact label, the statement, and a source line.", callout: "note" },
  { layout: "row{number:circle, stack#callout{label, body}}", name: "Numbered Fact", description: "A circled number beside a labelled fact.", callout: "note" },
  { layout: "band#accent{stack{label, body}}", name: "Accent Fact", description: "A short fact on a high-contrast band, with its label visible.", callout: "note" },
  { layout: "stack#callout{ornament:asterism, label, body}", name: "Paused Fact", description: "An asterism, then a labelled fact.", callout: "note" },
];

export const PRACTICE_SPECS: DesignSpec[] = [
  { layout: "stack#callout{label:chip, body, steps}", name: "Worked Steps", description: "A worked example with a label, the problem, and numbered steps.", callout: "info" },
  { layout: "stack#callout{label, formula, steps}", name: "Formula and Steps", description: "The formula is labelled, then the steps follow.", callout: "info" },
  { layout: "row{number:chip, stack#callout{label, body, steps}}", name: "Numbered Example", description: "An example number beside the problem and steps.", callout: "info" },
  { layout: "stack#callout{label:smallcaps, rule:short, body, rule:short, steps}", name: "Ruled Example", description: "Rules separate the problem from the steps.", callout: "info" },
  { layout: "row{stack#callout~48{label, body}, stack#callout{label:solution, steps}}", name: "Problem and Solution", description: "The problem and the solution sit in two columns.", callout: "info" },
  { layout: "stack#callout{label, body, lines:4}", name: "Prompt and Lines", description: "A prompt with four answer lines.", callout: "assessment" },
  { layout: "stack#callout{number:chip, body, lines:3}", name: "Numbered Lines", description: "A question number, the prompt, and three lines.", callout: "assessment" },
  { layout: "row{rail:thick, stack#callout{label, body, lines:4}}", name: "Rail Exercise", description: "A rail marks the exercise, with lines for the answer.", callout: "assessment" },
  { layout: "stack#callout{label:chip, rule:short, items:check}", name: "Checkbox Exercise", description: "A labelled list of items to check off.", callout: "activity" },
  { layout: "stack#callout{label, body, rule:dotted, lines:5}", name: "Dotted Answer Block", description: "Prompt, a dotted rule, and five answer lines.", callout: "assessment" },
  { layout: "stack#callout{label, badges, materials, steps}", name: "Investigation Card", description: "Time, level, and group, then materials and steps.", callout: "activity" },
  { layout: "stack#callout{number:chip, label, badges, steps}", name: "Numbered Activity", description: "An activity number, meta chips, and the steps.", callout: "activity" },
  { layout: "row{panel:tint~28, stack#callout{label, materials, steps}}", name: "Activity with Plate", description: "A plate for a sketch beside materials and steps.", callout: "activity" },
  { layout: "band#tint{stack{label, badges, steps}}", name: "Tinted Activity", description: "Label, meta chips, and steps on a tint.", callout: "activity" },
  { layout: "stack#callout{kicker:smallcaps, label, rule:short, materials, steps}", name: "Formal Investigation", description: "A formal activity heading, materials, and steps.", callout: "activity" },
  { layout: "stack#callout{label:chip, question, options}", name: "Multiple Choice", description: "A question with lettered options. Letters carry the choices.", callout: "assessment" },
  { layout: "stack#callout{row{number:chip, meta:marks}, question, options}", name: "Marked Question", description: "Question number, mark total, stem, and options.", callout: "assessment" },
  { layout: "stack#callout{label, question, lines:3}", name: "Short Answer", description: "A short-answer stem with three writing lines.", callout: "assessment" },
  { layout: "stack#callout{label:chip, items:pair}", name: "Match Pairs", description: "Two columns of pairs to match, with both sides written out.", callout: "assessment" },
  { layout: "stack#callout{label, table:plain, meta:credit}", name: "Rubric Table", description: "A small rubric table with a source line.", callout: "assessment" },
  { layout: "stack#callout{label, body, formula, steps, rule:short, meta:answer}", name: "Example with Answer", description: "Problem, formula, steps, and a labelled answer.", callout: "info" },
  { layout: "row{rail:thick, stack#callout{label, formula, steps}}", name: "Rail Formula", description: "A rail beside a labelled formula and its steps.", callout: "info" },
  { layout: "stack@center#callout{label:smallcaps, formula, steps}", name: "Centred Formula", description: "A centred formula block with the steps beneath.", callout: "info" },
  { layout: "corners{stack#callout{label, body, formula}}", name: "Framed Formula", description: "Corner marks around a problem and its formula.", callout: "info" },
  { layout: "stack#callout{number:modest, question, lines:4}", name: "Long Response", description: "A modest question number and four response lines.", callout: "assessment" },
  { layout: "row{number:display~16, stack#callout{question, meta:marks}}", name: "Display Question Number", description: "A large question number beside the stem and the mark total.", callout: "assessment" },
  { layout: "stack#callout{label:chip, question, options, meta:hint}", name: "Question with Hint", description: "Stem, options, and a hint labelled as a hint.", callout: "assessment" },
  { layout: "stack#callout{rule:thick, question, rule:hairline, lines:3}", name: "Ruled Question", description: "A heavy rule, the question, a hairline, and answer lines.", callout: "assessment" },
];

export const TABLE_SPECS: DesignSpec[] = [
  { layout: "stack{caption, table:grid}", name: "Captioned Grid", description: "A caption above a fully ruled table." },
  { layout: "stack{table:band, caption}", name: "Banded Header", description: "A solid header band, with the caption below the table." },
  { layout: "stack{label:chip, table:compare}", name: "Comparison Block", description: "A labelled comparison table with equal columns." },
  { layout: "stack{table:striped, caption}", name: "Striped Rows", description: "Alternate row surfaces and a caption." },
  { layout: "stack{table:plain, rule:short, caption}", name: "Open Textbook Table", description: "Horizontal rules only, a short rule, then the caption." },
  { layout: "stack{table:kv}", name: "Key and Value", description: "Two columns: the term and what it means." },
  { layout: "stack{label:smallcaps, table:stats}", name: "Stat Row", description: "A few large figures with their labels underneath." },
  { layout: "stack{table:rules, caption}", name: "Rule-Only Table", description: "Header and body separated by rules, without a vertical grid." },
  { layout: "stack{table:emphasis, caption}", name: "Emphasised First Column", description: "The first column is tinted so the row labels stay readable in gray." },
  { layout: "stack{kicker:smallcaps, table:grid}", name: "Labelled Grid", description: "A small-caps label above a standard grid." },
  { layout: "row{rail:thick, stack{caption, table:plain}}", name: "Rail Table", description: "A rail beside a caption and an open table." },
  { layout: "stack{table:band}", name: "Header Band Only", description: "A banded header and plain body, with no caption." },
  { layout: "stack#surface{table:kv, meta:credit}", name: "Surface Key Table", description: "Key-value pairs on a surface, plus a credit line." },
  { layout: "stack{caption, table:compare, rule:hairline}", name: "Closed Comparison", description: "Caption, comparison columns, and a hairline close." },
  { layout: "corners{stack{table:grid}}", name: "Cornered Table", description: "Corner marks around a compact grid." },
  { layout: "stack{label:chip, table:stats, caption}", name: "Called-Out Figures", description: "A chip, a row of figures, and a caption." },
];

export const FIGURE_SPECS: DesignSpec[] = [
  { layout: "stack{figure:frame, rule:short, caption}", name: "Frame and Rule", description: "A rectangular frame, a short rule, and the caption." },
  { layout: "row{figure:frame~58, stack{label:chip, caption, meta:credit}}", name: "Wide Frame, Side Caption", description: "The frame takes most of the width. Caption and credit sit beside it." },
  { layout: "stack{figure:plate, caption}", name: "Plate", description: "A plate with an inner margin and a caption beneath." },
  { layout: "stack{label:chip, figure:rounded, caption}", name: "Rounded Figure", description: "A figure chip, a rounded frame, and the caption." },
  { layout: "stack{figure:circle, caption}", name: "Circular Crop", description: "A circular frame for a portrait or specimen, with a caption." },
  { layout: "corners{stack{figure:frame, caption}}", name: "Cornered Figure", description: "Corner marks around the frame and its caption." },
  { layout: "stack{figure:diagram, rule:hairline, caption}", name: "Diagram Frame", description: "A diagram placeholder, a hairline, and the caption." },
  { layout: "stack{kicker:smallcaps, figure:frame, caption}", name: "Labelled Figure", description: "A small-caps figure label, the frame, and the caption." },
  { layout: "row{stack~36{caption, meta:credit}, figure:plate}", name: "Caption Then Plate", description: "The caption leads. The plate sits to the right." },
  { layout: "stack{figure:rounded, meta:credit}", name: "Rounded with Credit", description: "A rounded frame and a credit, without a long caption." },
  { layout: "stack#surface{figure:diagram, caption}", name: "Surface Diagram", description: "A diagram on a surface card with its caption." },
  { layout: "stack{number:chip, figure:frame, caption}", name: "Numbered Frame", description: "A figure number chip, the frame, and the caption." },
  { layout: "stack{figure:plate, rule:double, caption}", name: "Plate and Double Rule", description: "A plate closed by a double rule and the caption." },
  { layout: "row{rail:thick, stack{figure:frame, caption}}", name: "Rail Figure", description: "A thick rail beside the frame and caption." },
  { layout: "stack@center{figure:circle, rule:short, caption}", name: "Centred Circle", description: "A centred circular frame, a short rule, and the caption." },
  { layout: "band#tint{stack{figure:diagram, caption}}", name: "Tinted Diagram", description: "A diagram and caption on a tinted ground." },
];

export const FURNITURE_SPECS: DesignSpec[] = [
  { layout: "rule:full", name: "Full Hairline", description: "A full-measure hairline for separating sections." },
  { layout: "rule:double", name: "Double Rule", description: "A double rule for a stronger pause." },
  { layout: "rule:dotted", name: "Dotted Rule", description: "A dotted rule, still clear in grayscale." },
  { layout: "rule:thick", name: "Heavy Rule", description: "A heavier rule for the start of a part." },
  { layout: "stack@center{rule:short, ornament:diamond, rule:short}", name: "Diamond Break", description: "Two short rules and a diamond, centred." },
  { layout: "stack@center{ornament:asterism}", name: "Asterism", description: "A centred asterism for a scene or section break." },
  { layout: "row@center{rule:flex, ornament:diamond, rule:flex}", name: "Diamond on the Measure", description: "A diamond centred in a full-measure rule." },
  { layout: "row@center{rule:flex, label:chip, rule:flex}", name: "Labelled Divider", description: "A chip label centred in a rule. The word carries the meaning." },
  { layout: "label:chip", name: "Section Chip", description: "A small chip for a section or part label." },
  { layout: "number:chip", name: "Number Chip", description: "A standalone number chip for a step or item." },
  { layout: "stack@center{kicker:smallcaps, rule:short}", name: "Centred Part Label", description: "A small-caps part label and a short rule." },
  { layout: "row{label:chip, rule:flex}", name: "Chip into Rule", description: "A label chip that runs into a rule." },
  { layout: "row{ornament:square, label:smallcaps}", name: "Square and Label", description: "A square mark and a small-caps label." },
  { layout: "stack{rule:thick, rule:hairline}", name: "Thick-Thin Pair", description: "A thick rule stacked with a hairline." },
  { layout: "row@center{rule:flex, ornament:asterism, rule:flex}", name: "Asterism on the Measure", description: "An asterism centred in a full rule." },
  { layout: "corners{label:chip}", name: "Cornered Label", description: "Corner marks around a short label." },
  { layout: "row{kicker:smallcaps, rule:flex, meta:page}", name: "Part and Folio", description: "A part label, a rule, and a page number. Useful in contents lines." },
  { layout: "stack@center{rule:dotted, label:smallcaps, rule:dotted}", name: "Dotted Label Break", description: "A label between two dotted rules." },
  { layout: "band#accent{label:smallcaps}", name: "Accent Label Band", description: "A short accent band containing a small-caps label." },
  { layout: "row{number:circle, label:plain}", name: "Circled Step", description: "A circled number and a plain step label." },
  { layout: "stack{ornament:brackets}", name: "Bracket Break", description: "A light bracket ornament used as a pause." },
  { layout: "row@end{meta:section, rule:short}", name: "Next Section Cue", description: "A short cue toward the next section, aligned to the end of the line." },
];

export const SPEC_GROUPS = [
  { role: "chapter" as const, specs: CHAPTER_SPECS },
  { role: "heading" as const, specs: HEADING_SPECS },
  { role: "running" as const, specs: RUNNING_SPECS },
  { role: "body" as const, specs: BODY_SPECS },
  { role: "quote" as const, specs: QUOTE_SPECS },
  { role: "learning" as const, specs: LEARNING_SPECS },
  { role: "practice" as const, specs: PRACTICE_SPECS },
  { role: "table" as const, specs: TABLE_SPECS },
  { role: "figure" as const, specs: FIGURE_SPECS },
  { role: "furniture" as const, specs: FURNITURE_SPECS },
];
