/** Run against `next start`. Uses existing Playwright installation; no application dependency. */
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import ts from 'typescript';
const require = createRequire(import.meta.url);
for (const ext of ['.ts','.tsx']) require.extensions[ext]=(module,file)=>module._compile(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText,file);
const {useEditorStore}=require('../src/editor/stores/editorStore.ts');
const {createSmartComponentElement}=require('../src/editor/educational/smartComponentFactory.ts');
const {runFullPreflightScan}=require('../src/editor/publishing/preflightEngine.ts');
const {propagateMasterToPage,MASTER_PAGE_PRESETS}=require('../src/editor/layout/masterPageEngine.ts');
const {chromium}=require('playwright');
const base=useEditorStore.getState().books[0],pages=[],elements={};
for(let i=0;i<220;i++){
  const id=`audit-page-${i+1}`, headingId=`audit-heading-${i+1}`,textId=`audit-text-${i+1}`;
  pages.push({id,pageIndex:i,displayNumber:String(i+1),chapterId:`audit-chapter-${Math.floor(i/20)+1}`,elementIds:[headingId,textId],status:'Draft'});
  const make=(elementId,type,text,y,height,size)=>({id:elementId,pageId:id,type,category:'text',version:1,displayName:`${type} on page ${i+1}`,locked:false,hidden:false,transform:{x:54,y,width:480,height,rotation:0,zIndex:1},style:{fontFamily:type==='heading'?'Outfit':'Inter',fontSize:size,lineHeight:1.45,color:'#1e293b'},content:{text}});
  elements[headingId]=make(headingId,'heading',`Lesson ${i+1}: Observe, reason and explain`,60,40,20);
  elements[textId]=make(textId,'body',`Read the evidence carefully. Explain what you noticed, compare two possible answers, and test your reasoning with a partner. This is production audit page ${i+1}.`,120,80,11);
}
const chapters=Array.from({length:11},(_,i)=>({id:`audit-chapter-${i+1}`,unitId:'audit-unit',number:i+1,title:`Learning chapter ${i+1}`,learningObjectives:['Observe evidence','Explain reasoning'],pageIds:pages.slice(i*20,i*20+20).map(page=>page.id)}));
const book={...base,id:'production-audit-220',title:'220-page production audit',subject:'English',grade:'Grade 3',language:'English',pages,chapters,units:[{id:'audit-unit',number:1,title:'Evidence and reasoning',chapterIds:chapters.map(chapter=>chapter.id)}],masterPages:[],pageFrame:null};
const smart=createSmartComponentElement('learning-outcomes',pages[179].id,{x:54,y:240,width:480,customTitle:'Learning targets for Page 180'});elements[smart.id]=smart;pages[179].elementIds.push(smart.id);
const master={...MASTER_PAGE_PRESETS.Exercise,type:'Exercise',pageNumberPosition:'right',footerText:'Production audit workbook'};
const linked=propagateMasterToPage(master,pages[179],elements,book);book.masterPages=[master];pages[179]=linked.page;Object.assign(elements,linked.updatedElements);
assert.equal(runFullPreflightScan(book,elements).errorCount,0);
const payload={books:[book],activeBookId:book.id,activePageIndex:179,elements,publicationPresets:{},userCustomLayouts:{},savedAt:new Date().toISOString()};
fs.mkdirSync('artifacts',{recursive:true});fs.writeFileSync('artifacts/production-audit-220-book.json',JSON.stringify(payload,null,2));
const browser=await chromium.launch({headless:true,...(process.env.NEX_CHROMIUM_PATH?{executablePath:process.env.NEX_CHROMIUM_PATH}:{})});
const context=await browser.newContext({viewport:{width:1440,height:1000}}),page=await context.newPage(),errors=[];
page.on('pageerror',error=>errors.push(error.message));
page.on('console',message=>{if(message.type()==='error'||message.type()==='warning')console.log(`Browser ${message.type()}: ${message.text()}`);});
await page.addInitScript(payload=>{if(!localStorage.getItem('nex_maxx_book_studio_data_v1'))localStorage.setItem('nex_maxx_book_studio_data_v1',JSON.stringify(payload));},payload);
const url=process.env.NEX_AUDIT_URL||'http://localhost:3107';
try{
  await page.goto(url);await page.getByRole('textbox',{name:'Click to rename book'}).waitFor();
  await page.waitForFunction(title => document.querySelector('input[title="Click to rename book"]')?.value === title, book.title);
  assert.equal(await page.getByRole('textbox',{name:'Click to rename book'}).inputValue(),book.title);
  await page.getByRole('tab',{name:'Pages',exact:true}).click();
  assert.equal(await page.getByRole('spinbutton',{name:'Go to physical page'}).inputValue(),'180');
  assert.ok(await page.getByText('Page 180',{exact:true}).count()>0);
  assert.equal(await page.getByRole('button',{name:/^Go to page /}).count(),24);
  await page.getByRole('button',{name:'Fit page',exact:true}).click();
  await page.locator('#element-audit-heading-180').dblclick();
  await page.locator('[contenteditable="true"]').fill('Lesson 180: A durable edit on an isolated page');
  await page.getByTitle('Done Editing (Escape or Cmd+Enter)').click();
  assert.ok((await page.locator('#element-audit-heading-180').innerText()).includes('A durable edit'));
  await page.getByTitle('Undo (Ctrl/Cmd + Z)').click();
  assert.ok((await page.locator('#element-audit-heading-180').innerText()).includes('Observe, reason and explain'));
  assert.equal(await page.getByRole('button',{name:/^Go to page /}).count(),24);
  await page.screenshot({path:'artifacts/production-audit-page-180.png'}); console.log('220-page workspace: Page 180 visible; 24 strip previews mounted.');
  await page.getByRole('button',{name:'Layout',exact:true}).click();await page.getByRole('button',{name:'Preflight Print Scan...'}).click();
  await page.getByText('LAYOUT CHECKS PASSED',{exact:true}).waitFor({timeout:30000});
  await page.getByRole('button',{name:'Close preflight'}).click();
  // Confirm a real IndexedDB commit; stale localStorage must not win after reload.
  const title='220-page audit · durable local edit';
  await page.getByRole('textbox',{name:'Click to rename book'}).fill(title);
  await page.waitForFunction(async title=>new Promise(resolve=>{const req=indexedDB.open('nex_maxx_book_studio_db',1);req.onsuccess=()=>{const db=req.result;const read=db.transaction('workspace').objectStore('workspace').get('active_workspace');read.onsuccess=()=>{const ok=read.result?.books?.[0]?.title===title;db.close();resolve(ok);};};req.onerror=()=>resolve(false);}),title);
  await page.reload();await page.getByRole('textbox',{name:'Click to rename book'}).waitFor();
  assert.equal(await page.getByRole('textbox',{name:'Click to rename book'}).inputValue(),title);
  await page.waitForFunction(async()=>{const cache=await caches.open('nex-book-studio-offline-v1');return navigator.serviceWorker.controller&&await cache.match('/')&&await cache.match('/fonts/manifest.json')&&(await cache.keys()).filter(key=>new URL(key.url).pathname.startsWith('/fonts/')).length>=16;},undefined,{timeout:30000});
  console.log('IndexedDB recovery and offline cache confirmed.');
  await context.setOffline(true);await page.reload();await page.getByRole('textbox',{name:'Click to rename book'}).waitFor();
  assert.equal(await page.getByRole('textbox',{name:'Click to rename book'}).inputValue(),title);
  await page.getByRole('button',{name:'Layout',exact:true}).click();await page.getByRole('button',{name:'Preflight Print Scan...'}).click();
  await page.getByText('LAYOUT CHECKS PASSED',{exact:true}).waitFor({timeout:30000});await page.getByRole('button',{name:'Close preflight'}).click();
  console.log("Offline reload and worker preflight passed.");
  // Selected-pages font-embedded export must respect scope while fully offline.
  await page.getByRole('button',{name:'Export',exact:true}).click();await page.getByRole('button',{name:/Selected Pages\s*Custom range/}).click();
  await page.locator('input[placeholder="1-5"]').fill('180-182');
  const popupPromise=page.waitForEvent('popup');
  await page.getByRole('button',{name:'Export Print Layout Proof'}).last().click();
  const proof=await popupPromise;await proof.waitForFunction(()=>document.querySelectorAll('section').length===3,{timeout:30000});
  await proof.evaluate(()=>document.fonts.ready);
  await proof.pdf({path:'artifacts/production-audit-selected-proof.pdf',printBackground:true,preferCSSPageSize:true});
  const selectedCount=await proof.locator('section').count();assert.equal(selectedCount,3);
  await page.getByRole('button',{name:'Export',exact:true}).click();
  await page.getByRole('button',{name:/Chapter PDF\s*Single chapter/}).click();
  await page.locator('select').filter({has:page.locator('option[value="audit-chapter-9"]')}).selectOption('audit-chapter-9');
  const chapterPromise=page.waitForEvent('popup');
  await page.getByRole('button',{name:'Export Print Layout Proof'}).click();
  const chapterProof=await chapterPromise;
  await chapterProof.waitForFunction(()=>document.querySelectorAll('section').length===20,undefined,{timeout:30000});
  await chapterProof.evaluate(()=>document.fonts.ready);
  await chapterProof.pdf({path:'artifacts/production-audit-chapter-proof.pdf',printBackground:true,preferCSSPageSize:true});
  await page.getByRole('button',{name:'Export',exact:true}).click();
  await page.getByRole('button',{name:/Complete Book/}).click();
  const completePromise=page.waitForEvent('popup');
  await page.getByRole('button',{name:'Export Print Layout Proof'}).click();
  const completeProof=await completePromise;
  await completeProof.waitForFunction(()=>document.querySelectorAll('section').length===220,{timeout:60000});
  await completeProof.evaluate(()=>document.fonts.ready);
  await completeProof.pdf({path:'artifacts/production-audit-complete-proof.pdf',printBackground:true,preferCSSPageSize:true});
  const pdfAudit=JSON.parse(execFileSync(process.env.NEX_AUDIT_PYTHON||'python3',['scripts/auditProductionPdfs.py'],{encoding:'utf8'}));
  assert.deepEqual(errors,[]);
  const result={pageCount:220,elementCount:Object.keys(elements).length,visibleStripPages:24,editedPage:180,pageEditAndUndo:true,indexedDbRecovery:true,offlineReload:true,offlineWorkerPreflight:true,offlineSelectedPdfPages:pdfAudit.selected.pages,offlineChapterPdfPages:pdfAudit.chapter.pages,offlineCompletePdfPages:pdfAudit.complete.pages,browserErrors:errors};
  fs.writeFileSync('artifacts/production-browser-audit.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(error){ await page.screenshot({path:'artifacts/production-audit-failure.png'}); console.error((await page.locator('body').innerText()).slice(-7000)); console.error(errors); console.error(await page.evaluate(async()=>({legacy:JSON.parse(localStorage.getItem('nex_maxx_book_studio_data_v1')||'null')?.books?.[0]?.title,indexed:await new Promise(resolve=>{const req=indexedDB.open('nex_maxx_book_studio_db',1);req.onsuccess=()=>{const read=req.result.transaction('workspace').objectStore('workspace').get('active_workspace');read.onsuccess=()=>resolve(read.result?.books?.[0]?.title);};})}))); throw error; }finally{await browser.close();}
