import { ElementPreset } from "../../domain/element/types";
import { picturePresets } from "../media/picturePresetCatalog";
import { smartQrPresets } from "../media/smartQr";
import { buildDesignPresets } from "../design/buildLibrary";

const LEGACY_ELEMENT_PRESETS: Record<string, ElementPreset> = {
  // ================= TEXT PRESETS =================
  "preset-ch-title": {
    id: "preset-ch-title",
    type: "heading",
    name: "Chapter Title",
    category: "text",
    variant: "display",
    description: "Bold title for chapter openings with high visual hierarchy",
    icon: "Heading1",
    defaultTransform: { width: 480, height: 48, rotation: 0 },
    defaultStyle: {
      fontSize: 26,
      fontWeight: 700,
      color: "#0f172a",
      textAlign: "left",
      lineHeight: 1.15,
    },
    defaultContent: {
      text: "Chapter 1: The Building Blocks of Life",
    },
  },

  "preset-section-heading": {
    id: "preset-section-heading",
    type: "subheading",
    name: "Section Heading",
    category: "text",
    variant: "primary",
    description: "Major section division with topic title",
    icon: "Heading2",
    defaultTransform: { width: 440, height: 32, rotation: 0 },
    defaultStyle: {
      fontSize: 16,
      fontWeight: 600,
      color: "#059669",
      textAlign: "left",
      lineHeight: 1.25,
    },
    defaultContent: {
      text: "1.1 Understanding Plant Cells & Chloroplasts",
    },
  },

  "preset-body-paragraph": {
    id: "preset-body-paragraph",
    type: "body",
    name: "Academic Body Paragraph",
    category: "text",
    variant: "standard",
    description: "Clean readable textbook body typography with optimal measure",
    icon: "AlignLeft",
    defaultTransform: { width: 480, height: 80, rotation: 0 },
    defaultStyle: {
      fontSize: 10.5,
      fontWeight: 400,
      color: "#334155",
      textAlign: "left",
      lineHeight: 1.5,
    },
    defaultContent: {
      text: "All living organisms are made up of basic microscopic structural units called cells. Plant cells are eukaryotic cells with a cell wall providing rigidity and chloroplasts that enable the remarkable biochemical process of photosynthesis.",
    },
  },

  // ================= EDUCATIONAL CALLOUTS =================
  "preset-learning-objectives": {
    id: "preset-learning-objectives",
    type: "learningObjectives",
    name: "Learning Objectives",
    category: "educational",
    variant: "accent-card",
    description: "Curriculum outcome badges for lesson intro",
    icon: "Target",
    defaultTransform: { width: 480, height: 90, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#f0f9ff",
      borderColor: "#0284c7",
      borderWidth: 1.5,
      borderStyle: "solid",
      borderRadius: 8,
      padding: { top: 12, right: 14, bottom: 12, left: 14 },
      color: "#0369a1",
      fontSize: 9.5,
      lineHeight: 1.4,
    },
    defaultContent: {
      title: "LEARNING GOALS",
      items: [
        "Identify the primary organelles of a typical plant cell.",
        "Contrast plant cell walls with animal cell membranes.",
        "Explain how chloroplasts capture radiant solar energy.",
      ],
    },
  },

  "preset-did-you-know": {
    id: "preset-did-you-know",
    type: "didYouKnow",
    name: "Did You Know?",
    category: "educational",
    variant: "curiosity-box",
    description: "Engaging science and real-world trivia callout",
    icon: "Sparkles",
    defaultTransform: { width: 230, height: 110, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#fefce8",
      borderColor: "#ca8a04",
      borderWidth: 1.5,
      borderRadius: 10,
      padding: { top: 10, right: 12, bottom: 10, left: 12 },
      color: "#713f12",
      fontSize: 9,
      lineHeight: 1.35,
    },
    defaultContent: {
      title: "DID YOU KNOW?",
      body: "Giant redwood trees can transport water from roots up to needles over 350 feet in the air using specialized capillary xylem vessels without any mechanical pumps!",
    },
  },

  "preset-key-concept": {
    id: "preset-key-concept",
    type: "keyConcept",
    name: "Key Concept Card",
    category: "educational",
    variant: "hero-pill",
    description: "Highlighted essential definition or law",
    icon: "Key",
    defaultTransform: { width: 480, height: 75, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#fdf4ff",
      borderColor: "#c026d3",
      borderWidth: 1.5,
      borderRadius: 8,
      padding: { top: 10, right: 14, bottom: 10, left: 14 },
      color: "#701a75",
      fontSize: 10,
      lineHeight: 1.4,
    },
    defaultContent: {
      title: "KEY SCIENTIFIC PRINCIPLE",
      body: "Photosynthesis: The biological process wherein plants synthesize glucose from carbon dioxide and water utilizing light energy absorbed by chlorophyll.",
    },
  },

  "preset-hands-on-activity": {
    id: "preset-hands-on-activity",
    type: "activity",
    name: "Hands-on Activity",
    category: "educational",
    variant: "playful-amber",
    description: "Interactive classroom and lab investigation",
    icon: "Beaker",
    defaultTransform: { width: 480, height: 130, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#fffbeb",
      borderColor: "#f59e0b",
      borderWidth: 1.5,
      borderRadius: 10,
      padding: { top: 12, right: 14, bottom: 12, left: 14 },
      color: "#78350f",
      fontSize: 9.5,
      lineHeight: 1.4,
    },
    defaultContent: {
      title: "ACTIVITY: Observing Onion Peel Cells",
      materials: "Fresh red onion, glass slide, iodine solution, dropper, light microscope.",
      steps: [
        "1. Peel a translucent epidermal membrane from inner onion scale.",
        "2. Mount flat onto microscope slide with one drop of iodine stain.",
        "3. Focus under 40x objective lens to observe the rectangular brick-like cells.",
      ],
    },
  },

  "preset-summary-card": {
    id: "preset-summary-card",
    type: "summary",
    name: "Chapter Summary",
    category: "educational",
    variant: "recap-slate",
    description: "End-of-chapter consolidation and memory hooks",
    icon: "CheckCircle2",
    defaultTransform: { width: 480, height: 110, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#f8fafc",
      borderColor: "#64748b",
      borderWidth: 1.5,
      borderRadius: 8,
      padding: { top: 12, right: 14, bottom: 12, left: 14 },
      color: "#0f172a",
      fontSize: 9.5,
      lineHeight: 1.4,
    },
    defaultContent: {
      title: "LET'S RECAP & REMEMBER",
      items: [
        "Cells are the fundamental units of all known living systems.",
        "Plant cells have a cellulose wall, chloroplasts, and a large central vacuole.",
        "Chlorophyll molecules capture photons to split water and fix atmospheric CO₂.",
      ],
    },
  },

  // ================= ASSESSMENT PRESETS =================
  "preset-mcq-question": {
    id: "preset-mcq-question",
    type: "mcq",
    name: "Multiple Choice Question",
    category: "assessment",
    variant: "structured",
    description: "Standard curriculum multiple-choice question with 4 options",
    icon: "HelpCircle",
    defaultTransform: { width: 480, height: 105, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 6,
      padding: { top: 10, right: 12, bottom: 10, left: 12 },
      fontSize: 9.5,
      color: "#1e293b",
    },
    defaultContent: {
      questionNumber: "Q1",
      questionText: "Which organelle is exclusively found in plant cells and gives leaves their green color?",
      options: [
        "A) Mitochondria",
        "B) Chloroplast",
        "C) Golgi Apparatus",
        "D) Endoplasmic Reticulum",
      ],
      correctAnswerIndex: 1,
      marks: 1,
    },
  },

  "preset-fill-blank": {
    id: "preset-fill-blank",
    type: "fillInBlank",
    name: "Fill in the Blanks",
    category: "assessment",
    variant: "practice-row",
    description: "Fill-in line exercise for student notebooks",
    icon: "Edit3",
    defaultTransform: { width: 480, height: 70, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#e2e8f0",
      borderWidth: 1,
      borderRadius: 6,
      padding: { top: 10, right: 12, bottom: 10, left: 12 },
      fontSize: 9.5,
      color: "#1e293b",
    },
    defaultContent: {
      questionNumber: "Q2",
      sentence: "The rigid outer protective layer present in plant cells is known as the _______________________.",
      answer: "Cell Wall",
      marks: 1,
    },
  },

  // ================= WORKBOOK PRESETS =================
  "preset-writing-lines": {
    id: "preset-writing-lines",
    type: "writingLines",
    name: "Handwriting Rule Lines",
    category: "workbook",
    variant: "ruled-4-line",
    description: "Exact 4-line or double-line calligraphy guidelines for student writing practice",
    icon: "Menu",
    defaultTransform: { width: 480, height: 80, rotation: 0 },
    defaultStyle: {
      borderColor: "#94a3b8",
      borderWidth: 0.75,
      lineHeight: 18,
    },
    defaultContent: {
      lineCount: 4,
      lineType: "four-line",
      samplePrompt: "Write two key functions of the plant cell wall:",
    },
  },

  "preset-drawing-box": {
    id: "preset-drawing-box",
    type: "drawingBox",
    name: "Illustration & Drawing Frame",
    category: "workbook",
    variant: "sketch-frame",
    description: "Dotted workbook border for student scientific diagrams",
    icon: "Square",
    defaultTransform: { width: 230, height: 160, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#fafaf9",
      borderColor: "#78716c",
      borderWidth: 1.5,
      borderStyle: "dashed",
      borderRadius: 8,
      padding: { top: 8, right: 8, bottom: 8, left: 8 },
    },
    defaultContent: {
      title: "Diagram Box",
      prompt: "Draw and label a plant cell with chloroplast, nucleus and vacuole.",
    },
  },

  // ================= MEDIA PRESETS =================
  "preset-image-frame": {
    id: "preset-image-frame",
    type: "image",
    name: "Scientific Illustration Frame",
    category: "media",
    variant: "captioned-image",
    description: "High-resolution diagram with caption and print DPI preflight tracking",
    icon: "Image",
    defaultTransform: { width: 230, height: 170, rotation: 0 },
    defaultStyle: {
      borderRadius: 6,
      borderColor: "#e2e8f0",
      borderWidth: 1,
      backgroundColor: "#f1f5f9",
    },
    defaultContent: {
      src: "https://images.unsplash.com/photo-1530595467537-0b5996c41f2d?w=800&auto=format&fit=crop&q=80",
      alt: "Plant cells under microscope showing chlorophyll discs",
      caption: "Fig 1.1: Microscopic view of Elodea leaf cells displaying green chloroplasts.",
      rawWidthPx: 1200,
      rawHeightPx: 800,
    },
  },

  "preset-qr-code": {
    id: "preset-qr-code",
    type: "qrCode",
    name: "Digital Extension QR Code",
    category: "media",
    variant: "interactive-link",
    description: "Scan link for video lesson, 3D AR model, or interactive quiz",
    icon: "QrCode",
    defaultTransform: { width: 85, height: 95, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#0284c7",
      borderWidth: 1,
      borderRadius: 6,
      padding: { top: 6, right: 6, bottom: 6, left: 6 },
    },
    defaultContent: {
      targetUrl: "https://curriculum.nexmaxx.edu/science/g5/cells-3d",
      label: "SCAN FOR 3D AR SIMULATION",
    },
  },

  // ================= DATA PRESETS =================
  "preset-comparison-table": {
    id: "preset-comparison-table",
    type: "comparison",
    name: "Science Comparison Table",
    category: "data",
    variant: "two-column",
    description: "Side-by-side contrast between plant and animal cells",
    icon: "Columns",
    defaultTransform: { width: 480, height: 110, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 6,
      fontSize: 9,
    },
    defaultContent: {
      headers: ["Organelle / Feature", "Plant Cell", "Animal Cell"],
      rows: [
        ["Cell Wall", "Present (Rigid Cellulose)", "Absent"],
        ["Chloroplasts", "Present for photosynthesis", "Absent"],
        ["Vacuole", "Single large central vacuole", "Small or absent"],
      ],
    },
  },

  // ================= DECORATIVE PRESETS =================
  "preset-unit-banner": {
    id: "preset-unit-banner",
    type: "badge",
    name: "Unit Header Banner",
    category: "decorative",
    variant: "pill",
    description: "Curriculum unit badge with bold theme coloring",
    icon: "Bookmark",
    defaultTransform: { width: 486, height: 32, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#065f46",
      borderRadius: 6,
      color: "#ffffff",
      fontSize: 10,
      fontWeight: 700,
      textAlign: "center",
      padding: { top: 8, right: 12, bottom: 8, left: 12 },
    },
    defaultContent: {
      text: "UNIT 1 • LIVING SYSTEMS & CELLULAR BIOLOGY",
    },
  },

  "preset-lab-card": {
    id: "preset-lab-card",
    type: "activity",
    name: "Laboratory Protocol Card",
    category: "educational",
    variant: "lab-investigation",
    description: "Structured laboratory protocol with safety rules and steps",
    icon: "Beaker",
    defaultTransform: { width: 486, height: 160, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#f0fdf4",
      borderColor: "#22c55e",
      borderWidth: 1.5,
      borderRadius: 8,
      padding: { top: 12, right: 14, bottom: 12, left: 14 },
      color: "#14532d",
    },
    defaultContent: {
      title: "LAB EXPERIMENT PROTOCOL",
      materials: "Beaker, distilled water, test tubes, optical microscope, slide.",
      steps: [
        "1. Prepare wet mount of biological specimen.",
        "2. Adjust condenser iris diaphragm for contrast.",
        "3. Record microscopic observations in lab workbook.",
      ],
    },
  },

  "preset-page-divider": {
    id: "preset-page-divider",
    type: "divider",
    name: "Ornamental Section Divider",
    category: "decorative",
    variant: "accent-bar",
    description: "Clean gradient horizontal divider",
    icon: "Minus",
    defaultTransform: { width: 480, height: 3, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#059669",
      borderRadius: 2,
    },
    defaultContent: {},
  },

  "preset-shape-rect": {
    id: "preset-shape-rect",
    type: "shape",
    name: "Vector Rectangle",
    category: "decorative",
    variant: "vector",
    description: "Vector rectangle with customizable fill, stroke, and corner radius",
    icon: "Square",
    defaultTransform: { width: 180, height: 120, rotation: 0 },
    defaultStyle: {
      shapeType: "rectangle",
      backgroundColor: "#e0e7ff",
      borderColor: "#4338ca",
      borderWidth: 2,
      borderStyle: "solid",
      borderRadius: 8,
    },
    defaultContent: {},
  },

  "preset-shape-circle": {
    id: "preset-shape-circle",
    type: "shape",
    name: "Vector Ellipse",
    category: "decorative",
    variant: "vector",
    description: "Vector circle/ellipse with fill and stroke",
    icon: "Circle",
    defaultTransform: { width: 140, height: 140, rotation: 0 },
    defaultStyle: {
      shapeType: "circle",
      backgroundColor: "#ecfdf5",
      borderColor: "#059669",
      borderWidth: 2,
      borderStyle: "solid",
      borderRadius: 9999,
    },
    defaultContent: {},
  },

  "preset-shape-star": {
    id: "preset-shape-star",
    type: "shape",
    name: "Vector Star",
    category: "decorative",
    variant: "vector",
    description: "5-point vector star badge",
    icon: "Star",
    defaultTransform: { width: 120, height: 120, rotation: 0 },
    defaultStyle: {
      shapeType: "star",
      backgroundColor: "#fef3c7",
      borderColor: "#d97706",
      borderWidth: 2,
      borderStyle: "solid",
    },
    defaultContent: {},
  },

  "preset-table-grid": {
    id: "preset-table-grid",
    type: "table",
    name: "Curriculum Data Table",
    category: "data",
    variant: "grid",
    description: "Editable curriculum data table with rows and columns",
    icon: "Table",
    defaultTransform: { width: 486, height: 150, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 6,
    },
    defaultContent: {
      headers: ["Column 1", "Column 2", "Column 3"],
      rows: [
        ["Data A1", "Data B1", "Data C1"],
        ["Data A2", "Data B2", "Data C2"],
        ["Data A3", "Data B3", "Data C3"],
      ],
    },
  },

  // ================= TITLES (Directive 35) =================
  "preset-title-minimal": {
    id: "preset-title-minimal",
    type: "heading",
    name: "Minimal Clean Title",
    category: "text",
    variant: "minimal",
    description: "Crisp typography with understated aesthetic",
    icon: "Heading1",
    defaultTransform: { width: 480, height: 38, rotation: 0 },
    defaultStyle: { fontSize: 22, fontWeight: 600, color: "#1e293b", letterSpacing: -0.5 },
    defaultContent: { text: "Chapter Overview" },
  },
  "preset-title-editorial": {
    id: "preset-title-editorial",
    type: "heading",
    name: "Editorial Serif Title",
    category: "text",
    variant: "editorial",
    description: "Classic serif typography for literature and humanities",
    icon: "Heading1",
    defaultTransform: { width: 480, height: 44, rotation: 0 },
    defaultStyle: { fontSize: 26, fontWeight: 700, color: "#1e1b4b", fontFamily: "Georgia, serif" },
    defaultContent: { text: "The Classical World" },
  },
  "preset-title-underlined": {
    id: "preset-title-underlined",
    type: "heading",
    name: "Underlined Accent Title",
    category: "text",
    variant: "underlined",
    description: "Headline with bold secondary underline accent",
    icon: "Heading1",
    defaultTransform: { width: 480, height: 42, rotation: 0 },
    defaultStyle: { fontSize: 22, fontWeight: 700, color: "#0f172a", textDecoration: "underline" },
    defaultContent: { text: "Fundamental Properties" },
  },
  "preset-title-numbered": {
    id: "preset-title-numbered",
    type: "heading",
    name: "Numbered Section Title",
    category: "text",
    variant: "numbered",
    description: "Section headline preceded by unit/topic index",
    icon: "Heading2",
    defaultTransform: { width: 480, height: 34, rotation: 0 },
    defaultStyle: { fontSize: 17, fontWeight: 700, color: "#0284c7" },
    defaultContent: { text: "2.3 Chemical Equilibrium" },
  },
  "preset-title-accent-bar": {
    id: "preset-title-accent-bar",
    type: "heading",
    name: "Accent Bar Title",
    category: "text",
    variant: "accent-bar",
    description: "Title with left vertical accent bar for visual hierarchy",
    icon: "Heading1",
    defaultTransform: { width: 480, height: 38, rotation: 0 },
    defaultStyle: { fontSize: 20, fontWeight: 700, color: "#800020", padding: { top: 2, right: 6, bottom: 2, left: 12 } },
    defaultContent: { text: "Key Scientific Principles" },
  },
  "preset-title-oversized": {
    id: "preset-title-oversized",
    type: "heading",
    name: "Oversized Display Title",
    category: "text",
    variant: "oversized",
    description: "Hero display headline for chapter introductions",
    icon: "Heading1",
    defaultTransform: { width: 480, height: 56, rotation: 0 },
    defaultStyle: { fontSize: 34, fontWeight: 900, color: "#0f172a", lineHeight: 1.1 },
    defaultContent: { text: "MOTION & ENERGY" },
  },

  // ================= CALLOUTS (Directive 35) =================
  "preset-callout-remember": {
    id: "preset-callout-remember",
    type: "teacherNote",
    name: "Remember Callout",
    category: "educational",
    variant: "callout",
    description: "Highlighted memory badge reminding essential facts",
    icon: "Sparkles",
    defaultTransform: { width: 480, height: 70, rotation: 0 },
    defaultStyle: { backgroundColor: "#fef3c7", borderColor: "#f59e0b", borderWidth: 1.5, borderRadius: 8, padding: { top: 10, right: 12, bottom: 10, left: 12 } },
    defaultContent: { title: "REMEMBER", text: "Energy can neither be created nor destroyed; it only transforms from one form to another." },
  },
  "preset-callout-important": {
    id: "preset-callout-important",
    type: "warning",
    name: "Important Alert Callout",
    category: "educational",
    variant: "alert",
    description: "High-priority warning or safety instruction",
    icon: "AlertCircle",
    defaultTransform: { width: 480, height: 75, rotation: 0 },
    defaultStyle: { backgroundColor: "#fef2f2", borderColor: "#ef4444", borderWidth: 2, borderRadius: 8, padding: { top: 10, right: 12, bottom: 10, left: 12 } },
    defaultContent: { title: "IMPORTANT SAFETY NOTE", text: "Never add water directly to concentrated acid. Always add acid slowly to water while stirring." },
  },
  "preset-callout-tip": {
    id: "preset-callout-tip",
    type: "teacherNote",
    name: "Study Tip Callout",
    category: "educational",
    variant: "tip",
    description: "Pedagogical study tip for exam preparation",
    icon: "HelpCircle",
    defaultTransform: { width: 480, height: 65, rotation: 0 },
    defaultStyle: { backgroundColor: "#ecfdf5", borderColor: "#10b981", borderWidth: 1.5, borderRadius: 8, padding: { top: 8, right: 12, bottom: 8, left: 12 } },
    defaultContent: { title: "EXAM TIP", text: "Always double-check your units (metres vs kilometres) before entering values in the equation." },
  },

  // ================= IMAGE FRAMES (Directive 35) =================
  "preset-frame-rounded": {
    id: "preset-frame-rounded",
    type: "image",
    name: "Rounded Image Frame",
    category: "media",
    variant: "rounded",
    description: "Modern soft-cornered picture frame with 16pt border radius",
    icon: "Image",
    defaultTransform: { width: 360, height: 220, rotation: 0 },
    defaultStyle: { borderRadius: 16, borderColor: "#cbd5e1", borderWidth: 1 },
    defaultContent: { src: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=800&auto=format&fit=crop&q=80", caption: "Macro view of cellular leaf structure" },
  },
  "preset-frame-circle": {
    id: "preset-frame-circle",
    type: "image",
    name: "Circular Picture Frame",
    category: "media",
    variant: "circle",
    description: "Perfect circle avatar or biological specimen frame",
    icon: "Circle",
    defaultTransform: { width: 180, height: 180, rotation: 0 },
    defaultStyle: { borderRadius: 9999, borderColor: "#0284c7", borderWidth: 3 },
    defaultContent: { src: "https://images.unsplash.com/photo-1507668077129-56e32842fceb?w=400&auto=format&fit=crop&q=80", caption: "Scientist Portrait" },
  },
  "preset-frame-polaroid": {
    id: "preset-frame-polaroid",
    type: "image",
    name: "Polaroid Style Frame",
    category: "media",
    variant: "polaroid",
    description: "Vintage white photo border with handwritten style caption below",
    icon: "Image",
    defaultTransform: { width: 240, height: 280, rotation: 0 },
    defaultStyle: { backgroundColor: "#ffffff", borderColor: "#e2e8f0", borderWidth: 1, borderRadius: 4, padding: { top: 12, right: 12, bottom: 36, left: 12 }, boxShadow: "0 4px 6px -1px rgb(0 0 0 / 0.1)" },
    defaultContent: { src: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80", caption: "Field Expedition 2026" },
  },

  // ================= QUOTES (Directive 35) =================
  "preset-quote-large-mark": {
    id: "preset-quote-large-mark",
    type: "quote",
    name: "Large Mark Pullquote",
    category: "text",
    variant: "large-mark",
    description: "Editorial pullquote with oversized decorative quotation mark",
    icon: "Quote",
    defaultTransform: { width: 440, height: 90, rotation: 0 },
    defaultStyle: { fontSize: 13, fontStyle: "italic", color: "#1e1b4b", lineHeight: 1.5, fontFamily: "Georgia, serif" },
    defaultContent: { text: "“Science knows no country, because knowledge belongs to humanity, and is the torch which illuminates the world.” — Louis Pasteur" },
  },
  "preset-quote-highlighted": {
    id: "preset-quote-highlighted",
    type: "quote",
    name: "Highlighted Thought Box",
    category: "text",
    variant: "highlighted",
    description: "Subtle shaded background card featuring a central guiding question",
    icon: "Quote",
    defaultTransform: { width: 480, height: 75, rotation: 0 },
    defaultStyle: { backgroundColor: "#f8fafc", borderColor: "#800020", borderWidth: 1, borderRadius: 8, padding: { top: 12, right: 16, bottom: 12, left: 16 }, fontSize: 11, color: "#334155" },
    defaultContent: { text: "“Look deep into nature, and then you will understand everything better.” — Albert Einstein" },
  },

  // ================= SEMANTIC TEXTBOOK PRESETS (Part 12) =================
  "preset-worked-example": {
    id: "preset-worked-example",
    type: "worked-example",
    name: "Worked Example (STEM)",
    category: "educational",
    variant: "stem-step",
    description: "Step-by-step mathematical or scientific derivation card",
    icon: "BookOpen",
    defaultTransform: { width: 480, height: 130, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#ecfeff",
      borderColor: "#06b6d4",
      borderWidth: 1.5,
      borderRadius: 10,
      padding: { top: 12, right: 14, bottom: 12, left: 14 },
    },
    defaultContent: {
      title: "WORKED EXAMPLE 3.1",
      problem: "Calculate the kinetic energy of a 1,200 kg vehicle moving at 20 m/s.",
      formula: "KE = 1/2 · m · v²",
      steps: [
        "1. Identify known variables: m = 1,200 kg, v = 20 m/s.",
        "2. Substitute values: KE = 0.5 × 1,200 × (20)² = 600 × 400.",
        "3. Compute final energy: KE = 240,000 Joules (240 kJ).",
      ],
      solution: "240 kJ (Kilojoules)",
    },
  },

  "preset-vocabulary-card": {
    id: "preset-vocabulary-card",
    type: "vocabulary",
    name: "Vocabulary & Key Concept",
    category: "educational",
    variant: "lexicon",
    description: "Academic vocabulary block with pronunciation and usage",
    icon: "Key",
    defaultTransform: { width: 230, height: 115, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#faf5ff",
      borderColor: "#a855f7",
      borderWidth: 1.5,
      borderRadius: 10,
      padding: { top: 10, right: 12, bottom: 10, left: 12 },
    },
    defaultContent: {
      title: "KEY VOCABULARY",
      term: "Osmosis",
      phonetic: "ɒzˈməʊsɪs",
      partOfSpeech: "noun",
      definition: "Net movement of solvent molecules through a semipermeable membrane into higher solute concentration.",
      exampleSentence: "Plant root hair cells absorb groundwater through osmosis.",
    },
  },

  "preset-timeline-block": {
    id: "preset-timeline-block",
    type: "timeline",
    name: "Chronological Timeline",
    category: "educational",
    variant: "horizontal-track",
    description: "Historical milestones track across lesson themes",
    icon: "Clock",
    defaultTransform: { width: 480, height: 100, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 10,
      padding: { top: 10, right: 14, bottom: 10, left: 14 },
    },
    defaultContent: {
      title: "HISTORICAL DEVELOPMENT",
      events: [
        { year: "1665", title: "Robert Hooke", desc: "Discovers microscopic cells in cork." },
        { year: "1839", title: "Schwann & Schleiden", desc: "Propose universal cell theory." },
        { year: "1855", title: "Rudolf Virchow", desc: "All cells arise from pre-existing cells." },
      ],
    },
  },

  "preset-subjective-question": {
    id: "preset-subjective-question",
    type: "question",
    name: "Subjective Question & Rubric",
    category: "educational",
    variant: "curriculum-question",
    description: "Graded exercise question with Bloom level and answer lines",
    icon: "HelpCircle",
    defaultTransform: { width: 480, height: 110, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#ffffff",
      borderColor: "#f59e0b",
      borderWidth: 1.5,
      borderRadius: 8,
      padding: { top: 10, right: 12, bottom: 10, left: 12 },
    },
    defaultContent: {
      questionNumber: "Q3",
      category: "Analysis",
      marks: 3,
      bloomLevel: "Analyze",
      questionText: "Differentiate between plant and animal cells with respect to chloroplasts, cell walls, and vacuoles.",
      hint: "Recall which organelle is responsible for synthesizing glucose during daylight.",
    },
  },

  "preset-answer-area": {
    id: "preset-answer-area",
    type: "answer-area",
    name: "Student Answer Area",
    category: "educational",
    variant: "ruled-grid",
    description: "Spacious ruled space for student handwritten answers",
    icon: "Square",
    defaultTransform: { width: 480, height: 95, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#f8fafc",
      borderColor: "#cbd5e1",
      borderWidth: 1,
      borderRadius: 8,
      padding: { top: 8, right: 12, bottom: 8, left: 12 },
    },
    defaultContent: {
      title: "STUDENT RESPONSE SPACE",
      rubric: "Write in neat handwriting. Justify all claims.",
      lineCount: 5,
    },
  },

  "preset-activity-science": {
    id: "preset-activity-science",
    type: "activity",
    name: "Hands-on Investigation",
    category: "educational",
    variant: "lab-investigation",
    description: "Engaging inquiry lab activity with materials and duration badges",
    icon: "Beaker",
    defaultTransform: { width: 480, height: 135, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#f0fdf4",
      borderColor: "#10b981",
      borderWidth: 1.5,
      borderRadius: 12,
      padding: { top: 12, right: 14, bottom: 12, left: 14 },
    },
    defaultContent: {
      title: "INVESTIGATION: OSMOSIS IN POTATO SLICES",
      numberBadge: "Activity 02",
      duration: "25 min",
      difficulty: "Intermediate",
      groupType: "Pairs",
      materials: "Raw potato, salt solution, petri dishes, electronic balance.",
      steps: [
        "1. Cut equal cylinders of fresh potato and measure starting mass.",
        "2. Submerge in distilled water and 10% salt solution for 20 minutes.",
        "3. Blot dry, re-weigh, and calculate percentage mass change.",
      ],
    },
  },

  "preset-chapter-summary": {
    id: "preset-chapter-summary",
    type: "summary",
    name: "Chapter Summary Card",
    category: "educational",
    variant: "takeaways",
    description: "Comprehensive summary checklist of lesson core concepts",
    icon: "CheckCircle2",
    defaultTransform: { width: 480, height: 105, rotation: 0 },
    defaultStyle: {
      backgroundColor: "#f0fdf4",
      borderColor: "#059669",
      borderWidth: 1.5,
      borderRadius: 10,
      padding: { top: 10, right: 14, bottom: 10, left: 14 },
    },
    defaultContent: {
      title: "CHAPTER KEY TAKEAWAYS",
      items: [
        "Cells are the fundamental units of all living organisms.",
        "Plant cells possess cellulose cell walls, large central vacuoles, and chloroplasts.",
        "Diffusion and osmosis govern cellular transport across biological membranes.",
      ],
    },
  },

  "preset-page-folio": {
    id: "preset-page-folio",
    type: "page-number",
    name: "Running Header & Page Folio",
    category: "text",
    variant: "folio",
    description: "Standard book chapter folio and page numbering element",
    icon: "Bookmark",
    defaultTransform: { width: 480, height: 26, rotation: 0 },
    defaultStyle: {
      backgroundColor: "transparent",
    },
    defaultContent: {
      chapterTitle: "Chapter 1: The Cellular Basis of Life",
      pageNumber: 14,
    },
  },
};

export const ELEMENT_PRESETS: Record<string, ElementPreset> = {
  ...LEGACY_ELEMENT_PRESETS,
  ...smartQrPresets,
  ...picturePresets,
  ...buildDesignPresets(),
};

// Re-export Comprehensive 160+ Page Presets Library
export {
  ALL_PAGE_PRESETS,
  COMPREHENSIVE_PRESET_LIBRARY,
  PAGE_PRESETS_MAP,
  type PagePresetDefinition,
  type PresetSlot,
  type PresetRule,
} from "./presetsData";


