import { PageElement } from "../../domain/element/types";
import { ELEMENT_PRESETS } from "./presets";

export interface PageTemplate {
  id: string;
  name: string;
  category: "chapterOpen" | "concept" | "activity" | "assessment" | "workbook" | "summary";
  description: string;
  thumbnail: string;
  elements: Omit<PageElement, "id" | "pageId">[];
}

export const PAGE_TEMPLATES: PageTemplate[] = [
  // 1. Chapter Opener Template
  {
    id: "template-chapter-opener",
    name: "Chapter Opener: Hero & Outcomes",
    category: "chapterOpen",
    description: "Full chapter title, unit badge, learning objectives card, and hero illustration",
    thumbnail: "chapter-open",
    elements: [
      {
        type: "heading",
        category: "text",
        version: 1,
        displayName: "Chapter Title",
        transform: { x: 54, y: 72, width: 480, height: 48, rotation: 0, zIndex: 1 },
        style: ELEMENT_PRESETS["preset-ch-title"].defaultStyle,
        content: { text: "Chapter 1: The Marvel of Living Cells" },
        presetId: "preset-ch-title",
        locked: false,
        hidden: false,
      },
      {
        type: "divider",
        category: "decorative",
        version: 1,
        displayName: "Divider Bar",
        transform: { x: 54, y: 126, width: 480, height: 4, rotation: 0, zIndex: 2 },
        style: { backgroundColor: "#059669", borderRadius: 2 },
        content: {},
        presetId: "preset-page-divider",
        locked: false,
        hidden: false,
      },
      {
        type: "learningObjectives",
        category: "educational",
        version: 1,
        displayName: "Learning Objectives",
        transform: { x: 54, y: 142, width: 480, height: 90, rotation: 0, zIndex: 3 },
        style: ELEMENT_PRESETS["preset-learning-objectives"].defaultStyle,
        content: ELEMENT_PRESETS["preset-learning-objectives"].defaultContent,
        presetId: "preset-learning-objectives",
        locked: false,
        hidden: false,
      },
      {
        type: "image",
        category: "media",
        version: 1,
        displayName: "Hero Botanical Image",
        transform: { x: 54, y: 242, width: 480, height: 180, rotation: 0, zIndex: 4 },
        style: { borderRadius: 8, borderColor: "#cbd5e1", borderWidth: 1 },
        content: {
          src: "https://images.unsplash.com/photo-1518531933037-91b2f5f229cc?w=1000&auto=format&fit=crop&q=80",
          alt: "Macro botanical leaves capturing sunlight",
          caption: "Fig 1.0: Sunlight penetrating plant tissue initiates cellular photosynthesis.",
          rawWidthPx: 1600,
          rawHeightPx: 900,
        },
        presetId: "preset-image-frame",
        locked: false,
        hidden: false,
      },
      {
        type: "body",
        category: "text",
        version: 1,
        displayName: "Opening Narrative",
        transform: { x: 54, y: 435, width: 480, height: 85, rotation: 0, zIndex: 5 },
        style: ELEMENT_PRESETS["preset-body-paragraph"].defaultStyle,
        content: {
          text: "When Robert Hooke peered into his handcrafted brass microscope in 1665, he observed hollow microscopic honeycombs in a thin sliver of bottle cork. He named these tiny chambers 'cells'. Today, we recognize that every blade of grass, redwood giant, and living organism is an astonishing metropolis of interacting cells.",
        },
        presetId: "preset-body-paragraph",
        locked: false,
        hidden: false,
      },
    ],
  },

  // 2. Concept & Scientific Explanation Page
  {
    id: "template-concept-reading",
    name: "Scientific Concept & Diagram Split",
    category: "concept",
    description: "Section heading, explanatory paragraphs, microscopic diagram, and Did You Know box",
    thumbnail: "concept-split",
    elements: [
      {
        type: "subheading",
        category: "text",
        version: 1,
        displayName: "Section 1.1 Heading",
        transform: { x: 54, y: 54, width: 480, height: 32, rotation: 0, zIndex: 1 },
        style: ELEMENT_PRESETS["preset-section-heading"].defaultStyle,
        content: { text: "1.1 The Anatomy of a Plant Cell" },
        presetId: "preset-section-heading",
        locked: false,
        hidden: false,
      },
      {
        type: "body",
        category: "text",
        version: 1,
        displayName: "Main Concept Text",
        transform: { x: 54, y: 94, width: 230, height: 180, rotation: 0, zIndex: 2 },
        style: ELEMENT_PRESETS["preset-body-paragraph"].defaultStyle,
        content: {
          text: "Unlike animal cells, plant cells possess a tough outer wall made of cellulose fibers. This wall allows plants to stand upright without bones. Inside the cell membrane lies the cytoplasm, where disc-shaped chloroplasts float in fluid suspension, converting sunlight into chemical nourishment.",
        },
        presetId: "preset-body-paragraph",
        locked: false,
        hidden: false,
      },
      {
        type: "image",
        category: "media",
        version: 1,
        displayName: "Cell Anatomy Diagram",
        transform: { x: 300, y: 94, width: 234, height: 180, rotation: 0, zIndex: 3 },
        style: ELEMENT_PRESETS["preset-image-frame"].defaultStyle,
        content: ELEMENT_PRESETS["preset-image-frame"].defaultContent,
        presetId: "preset-image-frame",
        locked: false,
        hidden: false,
      },
      {
        type: "keyConcept",
        category: "educational",
        version: 1,
        displayName: "Key Concept Box",
        transform: { x: 54, y: 290, width: 480, height: 75, rotation: 0, zIndex: 4 },
        style: ELEMENT_PRESETS["preset-key-concept"].defaultStyle,
        content: ELEMENT_PRESETS["preset-key-concept"].defaultContent,
        presetId: "preset-key-concept",
        locked: false,
        hidden: false,
      },
      {
        type: "comparison",
        category: "data",
        version: 1,
        displayName: "Comparison Table",
        transform: { x: 54, y: 380, width: 480, height: 110, rotation: 0, zIndex: 5 },
        style: ELEMENT_PRESETS["preset-comparison-table"].defaultStyle,
        content: ELEMENT_PRESETS["preset-comparison-table"].defaultContent,
        presetId: "preset-comparison-table",
        locked: false,
        hidden: false,
      },
      {
        type: "didYouKnow",
        category: "educational",
        version: 1,
        displayName: "Trivia Callout",
        transform: { x: 54, y: 506, width: 370, height: 110, rotation: 0, zIndex: 6 },
        style: ELEMENT_PRESETS["preset-did-you-know"].defaultStyle,
        content: ELEMENT_PRESETS["preset-did-you-know"].defaultContent,
        presetId: "preset-did-you-know",
        locked: false,
        hidden: false,
      },
      {
        type: "qrCode",
        category: "media",
        version: 1,
        displayName: "AR Simulator Link",
        transform: { x: 440, y: 512, width: 94, height: 104, rotation: 0, zIndex: 7 },
        style: ELEMENT_PRESETS["preset-qr-code"].defaultStyle,
        content: ELEMENT_PRESETS["preset-qr-code"].defaultContent,
        presetId: "preset-qr-code",
        locked: false,
        hidden: false,
      },
    ],
  },

  // 3. Hands-On Activity & Lab Page
  {
    id: "template-activity-lab",
    name: "Hands-on Activity & Lab Investigation",
    category: "activity",
    description: "Step-by-step experiment instructions, safety note, and student drawing box",
    thumbnail: "activity-lab",
    elements: [
      {
        type: "subheading",
        category: "text",
        version: 1,
        displayName: "Lab Investigation Title",
        transform: { x: 54, y: 54, width: 480, height: 32, rotation: 0, zIndex: 1 },
        style: { ...ELEMENT_PRESETS["preset-section-heading"].defaultStyle, color: "#d97706" },
        content: { text: "1.2 Practical Lab: Exploring Cell Structures" },
        presetId: "preset-section-heading",
        locked: false,
        hidden: false,
      },
      {
        type: "activity",
        category: "educational",
        version: 1,
        displayName: "Activity Procedure",
        transform: { x: 54, y: 96, width: 480, height: 140, rotation: 0, zIndex: 2 },
        style: ELEMENT_PRESETS["preset-hands-on-activity"].defaultStyle,
        content: ELEMENT_PRESETS["preset-hands-on-activity"].defaultContent,
        presetId: "preset-hands-on-activity",
        locked: false,
        hidden: false,
      },
      {
        type: "drawingBox",
        category: "workbook",
        version: 1,
        displayName: "Observation Sketch Box",
        transform: { x: 54, y: 250, width: 230, height: 180, rotation: 0, zIndex: 3 },
        style: ELEMENT_PRESETS["preset-drawing-box"].defaultStyle,
        content: ELEMENT_PRESETS["preset-drawing-box"].defaultContent,
        presetId: "preset-drawing-box",
        locked: false,
        hidden: false,
      },
      {
        type: "writingLines",
        category: "workbook",
        version: 1,
        displayName: "Observation Notes Lines",
        transform: { x: 298, y: 250, width: 236, height: 180, rotation: 0, zIndex: 4 },
        style: ELEMENT_PRESETS["preset-writing-lines"].defaultStyle,
        content: {
          lineCount: 6,
          lineType: "four-line",
          samplePrompt: "Record your microscope observations:",
        },
        presetId: "preset-writing-lines",
        locked: false,
        hidden: false,
      },
    ],
  },

  // 4. Assessment & Practice Page
  {
    id: "template-assessment-practice",
    name: "Chapter Assessment & Evaluation",
    category: "assessment",
    description: "Curriculum assessment with Multiple Choice Questions and Fill-in-the-blanks",
    thumbnail: "assessment-grid",
    elements: [
      {
        type: "subheading",
        category: "text",
        version: 1,
        displayName: "Assessment Header",
        transform: { x: 54, y: 54, width: 480, height: 32, rotation: 0, zIndex: 1 },
        style: { ...ELEMENT_PRESETS["preset-section-heading"].defaultStyle, color: "#4f46e5" },
        content: { text: "Chapter Review & Self-Assessment" },
        presetId: "preset-section-heading",
        locked: false,
        hidden: false,
      },
      {
        type: "mcq",
        category: "assessment",
        version: 1,
        displayName: "Question 1",
        transform: { x: 54, y: 96, width: 480, height: 110, rotation: 0, zIndex: 2 },
        style: ELEMENT_PRESETS["preset-mcq-question"].defaultStyle,
        content: ELEMENT_PRESETS["preset-mcq-question"].defaultContent,
        presetId: "preset-mcq-question",
        locked: false,
        hidden: false,
      },
      {
        type: "mcq",
        category: "assessment",
        version: 1,
        displayName: "Question 2",
        transform: { x: 54, y: 218, width: 480, height: 110, rotation: 0, zIndex: 3 },
        style: ELEMENT_PRESETS["preset-mcq-question"].defaultStyle,
        content: {
          questionNumber: "Q2",
          questionText: "What is the primary substance that constitutes the plant cell wall?",
          options: [
            "A) Glycogen",
            "B) Cellulose",
            "C) Keratin",
            "D) Hemoglobin",
          ],
          correctAnswerIndex: 1,
          marks: 1,
        },
        presetId: "preset-mcq-question",
        locked: false,
        hidden: false,
      },
      {
        type: "fillInBlank",
        category: "assessment",
        version: 1,
        displayName: "Question 3",
        transform: { x: 54, y: 340, width: 480, height: 70, rotation: 0, zIndex: 4 },
        style: ELEMENT_PRESETS["preset-fill-blank"].defaultStyle,
        content: ELEMENT_PRESETS["preset-fill-blank"].defaultContent,
        presetId: "preset-fill-blank",
        locked: false,
        hidden: false,
      },
    ],
  },
];
